/* Generated By:JJTree&JavaCC: Do not edit this line. OgnlParserConstants.java */

namespace OGNL.Parser;

internal static class ParserConstants {
    public const int Ident = 64;

    public const int DynamicSub = 67;

    public const int CharLiteral = 73;

    public const int BackCharLiteral = 76;

    public const int StringLiteral = 79;

    public const int IntLiteral = 80;

    public const int FltLiteral = 81;
}
