using System.Globalization;
using System.Text;

/* Generated By:JJTree&JavaCC: Do not edit this line. OgnlParserTokenManager.java */
namespace OGNL.Parser;

internal class ParserTokenManager(JavaCharStream stream) : ParserConstants {
    /** Holds the last value computed by a constant token. */
    internal object literalValue;

    /** Holds the last character escaped or in a character literal. */
    private char charValue;

    /** Holds the last string literal parsed. */
    private StringBuilder stringBuffer;

    /** Converts an escape sequence into a character value. */
    private char EscapeChar()
    {
        var ofs = image.Length - 1;

        switch (image[ofs]) {
            case 'n': return '\n';
            case 'r': return '\r';
            case 't': return '\t';
            case 'b': return '\b';
            case 'f': return '\f';
            case '\\': return '\\';
            case '\'': return '\'';
            case '\"': return '\"';
        }

        // Otherwise, it's an octal number.  Find the backslash and convert.
        while (image[--ofs] != '\\') {
        }

        var value = 0;

        while (++ofs < image.Length)
            value = (value << 3) | (image[ofs] - '0');

        return (char)value;
    }

    private object MakeInt()
    {
        object result;
        var s = image.ToString();
        var ibase = 10;

        if (s[0] == '0')
            ibase = s.Length > 1 && (s[1] == 'x' || s[1] == 'X') ? 16 : 8;
        if (ibase == 16)
            s = s[2..]; // Trim the 0x off the front

        switch (s[^1]) {
            case 'l':
            case 'L':
            case 'h':
            case 'H':
                result = Util.ParseLong(s[..^1], ibase);

                break;

            default:
                result = (int)Util.ParseLong(s, ibase);

                break;
        }

        return result;
    }

    private object MakeFloat()
    {
        var s = image.ToString();

        switch (s[^1]) {
            case 'f':
            case 'F':
                return float.Parse(s.Substring(0, s.Length - 1));

            case 'b':
            case 'B':
                return decimal.Parse(s.Substring(0, s.Length - 1));

            case 'd':
            case 'D':
                s = s.Substring(0, s.Length - 1);
                goto default;
            default:
                // s = s.ToUpper () ;
                if (s.IndexOf('E') > 0 || s.IndexOf('e') > 0)
                    return double.Parse(s, NumberStyles.AllowExponent);
                else
                    return double.Parse(s);
        }
    }

    private int jjStopStringLiteralDfa_0(int pos, long active0)
    {
        switch (pos) {
            case 0:
                if ((active0 & 0x201c4055d555540L) != 0L) {
                    jjmatchedKind = 64;

                    return 1;
                }

                if ((active0 & 0x400000000000000L) != 0L)
                    return 1;
                if ((active0 & 0x10000000000000L) != 0L)
                    return 3;
                if ((active0 & 0x80000000000L) != 0L)
                    return 9;

                return -1;
            case 1:
                if ((active0 & 0x201c00550045500L) != 0L) {
                    if (jjmatchedPos != 1) {
                        jjmatchedKind = 64;
                        jjmatchedPos = 1;
                    }

                    return 1;
                }

                if ((active0 & 0x4000d510040L) != 0L)
                    return 1;

                return -1;
            case 2:
                if ((active0 & 0x1c40400004000L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 2;

                    return 1;
                }

                if ((active0 & 0x200000155041500L) != 0L)
                    return 1;

                return -1;
            case 3:
                if ((active0 & 0x1400400004000L) != 0L)
                    return 1;

                if ((active0 & 0x840000000000L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 3;

                    return 1;
                }

                return -1;
            case 4:
                if ((active0 & 0x800000000000L) != 0L)
                    return 1;

                if ((active0 & 0x40000000000L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 4;

                    return 1;
                }

                return -1;
            case 5:
                if ((active0 & 0x40000000000L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 5;

                    return 1;
                }

                return -1;
            case 6:
                if ((active0 & 0x40000000000L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 6;

                    return 1;
                }

                return -1;
            case 7:
                if ((active0 & 0x40000000000L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 7;

                    return 1;
                }

                return -1;
            case 8:
                if ((active0 & 0x40000000000L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 8;

                    return 1;
                }

                return -1;
            default:
                return -1;
        }
    }

    private int jjStartNfa_0(int pos, long active0)
    {
        return JjMoveNfa0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
    }

    private int JjStopAtPos(int pos, int kind)
    {
        jjmatchedKind = kind;
        jjmatchedPos = pos;

        return pos + 1;
    }

    private int jjStartNfaWithStates_0(int pos, int kind, int state)
    {
        jjmatchedKind = kind;
        jjmatchedPos = pos;

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            return pos + 1;
        }

        return JjMoveNfa0(state, pos + 1);
    }

    private int jjMoveStringLiteralDfa0_0()
    {
        switch ((int)curChar) {
            case 33:
                jjmatchedKind = 41;

                return jjMoveStringLiteralDfa1_0(0x20000L);
            case 34:
                return JjStopAtPos(0, 70);
            case 35:
                jjmatchedKind = 51;

                return jjMoveStringLiteralDfa1_0(0x6000000000000L);
            case 36:
                return jjStartNfaWithStates_0(0, 58, 1);
            case 37:
                return JjStopAtPos(0, 39);
            case 38:
                jjmatchedKind = 13;

                return jjMoveStringLiteralDfa1_0(0x80L);
            case 39:
                return JjStopAtPos(0, 69);
            case 40:
                return JjStopAtPos(0, 44);
            case 41:
                return JjStopAtPos(0, 45);
            case 42:
                return JjStopAtPos(0, 37);
            case 43:
                return JjStopAtPos(0, 35);
            case 44:
                return JjStopAtPos(0, 1);
            case 45:
                return JjStopAtPos(0, 36);
            case 46:
                return jjStartNfaWithStates_0(0, 43, 9);
            case 47:
                return JjStopAtPos(0, 38);
            case 58:
                return JjStopAtPos(0, 4);
            case 60:
                jjmatchedKind = 19;

                return jjMoveStringLiteralDfa1_0(0x20800000L);
            case 61:
                jjmatchedKind = 2;

                return jjMoveStringLiteralDfa1_0(0x8000L);
            case 62:
                jjmatchedKind = 21;

                return jjMoveStringLiteralDfa1_0(0x282000000L);
            case 63:
                return JjStopAtPos(0, 3);
            case 64:
                return JjStopAtPos(0, 56);
            case 91:
                return jjStartNfaWithStates_0(0, 52, 3);
            case 93:
                return JjStopAtPos(0, 53);
            case 94:
                return JjStopAtPos(0, 11);
            case 96:
                return JjStopAtPos(0, 68);
            case 97:
                return jjMoveStringLiteralDfa1_0(0x100L);
            case 98:
                return jjMoveStringLiteralDfa1_0(0x4400L);
            case 101:
                return jjMoveStringLiteralDfa1_0(0x10000L);
            case 102:
                return jjMoveStringLiteralDfa1_0(0x800000000000L);
            case 103:
                return jjMoveStringLiteralDfa1_0(0x4400000L);
            case 105:
                return jjMoveStringLiteralDfa1_0(0x40008000000L);
            case 108:
                return jjMoveStringLiteralDfa1_0(0x1100000L);
            case 110:
                return jjMoveStringLiteralDfa1_0(0x201000010040000L);
            case 111:
                return jjMoveStringLiteralDfa1_0(0x40L);
            case 115:
                return jjMoveStringLiteralDfa1_0(0x140000000L);
            case 116:
                return jjMoveStringLiteralDfa1_0(0x400000000000L);
            case 117:
                return jjMoveStringLiteralDfa1_0(0x400000000L);
            case 120:
                return jjMoveStringLiteralDfa1_0(0x1000L);
            case 123:
                return JjStopAtPos(0, 54);
            case 124:
                jjmatchedKind = 9;

                return jjMoveStringLiteralDfa1_0(0x20L);
            case 125:
                return JjStopAtPos(0, 55);
            case 126:
                return JjStopAtPos(0, 40);
            default:
                return JjMoveNfa0(0, 0);
        }
    }

    private int jjMoveStringLiteralDfa1_0(long active0)
    {
        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(0, active0);

            return 1;
        }

        switch ((int)curChar) {
            case 38:
                if ((active0 & 0x80L) != 0L)
                    return JjStopAtPos(1, 7);

                break;
            case 60:
                if ((active0 & 0x20000000L) != 0L)
                    return JjStopAtPos(1, 29);

                break;
            case 61:
                if ((active0 & 0x8000L) != 0L)
                    return JjStopAtPos(1, 15);

                if ((active0 & 0x20000L) != 0L)
                    return JjStopAtPos(1, 17);

                if ((active0 & 0x800000L) != 0L)
                    return JjStopAtPos(1, 23);

                if ((active0 & 0x2000000L) != 0L)
                    return JjStopAtPos(1, 25);

                break;
            case 62:
                if ((active0 & 0x80000000L) != 0L) {
                    jjmatchedKind = 31;
                    jjmatchedPos = 1;
                }

                return jjMoveStringLiteralDfa2_0(active0, 0x200000000L);
            case 97:
                return jjMoveStringLiteralDfa2_0(active0, 0x800000004000L);
            case 101:
                return jjMoveStringLiteralDfa2_0(active0, 0x200000000040000L);
            case 104:
                return jjMoveStringLiteralDfa2_0(active0, 0x140000000L);
            case 110:
                if ((active0 & 0x8000000L) != 0L) {
                    jjmatchedKind = 27;
                    jjmatchedPos = 1;
                }

                return jjMoveStringLiteralDfa2_0(active0, 0x40000000100L);
            case 111:
                return jjMoveStringLiteralDfa2_0(active0, 0x10001400L);
            case 113:
                if ((active0 & 0x10000L) != 0L)
                    return jjStartNfaWithStates_0(1, 16, 1);

                break;
            case 114:
                if ((active0 & 0x40L) != 0L)
                    return jjStartNfaWithStates_0(1, 6, 1);

                return jjMoveStringLiteralDfa2_0(active0, 0x4400000000000L);
            case 115:
                return jjMoveStringLiteralDfa2_0(active0, 0x400000000L);
            case 116:
                if ((active0 & 0x100000L) != 0L) {
                    jjmatchedKind = 20;
                    jjmatchedPos = 1;
                } else if ((active0 & 0x400000L) != 0L) {
                    jjmatchedKind = 22;
                    jjmatchedPos = 1;
                }

                return jjMoveStringLiteralDfa2_0(active0, 0x2000005000000L);
            case 117:
                return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L);
            case 124:
                if ((active0 & 0x20L) != 0L)
                    return JjStopAtPos(1, 5);

                break;
        }

        return jjStartNfa_0(0, active0);
    }

    private int jjMoveStringLiteralDfa2_0(long old0, long active0)
    {
        if ((active0 &= old0) == 0L)
            return jjStartNfa_0(0, old0);

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(1, active0);

            return 2;
        }

        switch ((int)curChar) {
            case 62:
                if ((active0 & 0x200000000L) != 0L)
                    return JjStopAtPos(2, 33);

                break;
            case 100:
                if ((active0 & 0x100L) != 0L)
                    return jjStartNfaWithStates_0(2, 8, 1);

                break;
            case 101:
                if ((active0 & 0x1000000L) != 0L)
                    return jjStartNfaWithStates_0(2, 24, 1);

                if ((active0 & 0x4000000L) != 0L)
                    return jjStartNfaWithStates_0(2, 26, 1);

                break;
            case 104:
                return jjMoveStringLiteralDfa3_0(active0, 0x2000400000000L);
            case 108:
                if ((active0 & 0x40000000L) != 0L)
                    return jjStartNfaWithStates_0(2, 30, 1);

                return jjMoveStringLiteralDfa3_0(active0, 0x1800000000000L);
            case 110:
                return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
            case 111:
                return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000L);
            case 113:
                if ((active0 & 0x40000L) != 0L)
                    return jjStartNfaWithStates_0(2, 18, 1);

                break;
            case 114:
                if ((active0 & 0x400L) != 0L)
                    return jjStartNfaWithStates_0(2, 10, 1);

                if ((active0 & 0x1000L) != 0L)
                    return jjStartNfaWithStates_0(2, 12, 1);

                if ((active0 & 0x100000000L) != 0L)
                    return jjStartNfaWithStates_0(2, 32, 1);

                break;
            case 115:
                return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L);
            case 116:
                if ((active0 & 0x10000000L) != 0L)
                    return jjStartNfaWithStates_0(2, 28, 1);

                break;
            case 117:
                return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L);
            case 119:
                if ((active0 & 0x200000000000000L) != 0L)
                    return jjStartNfaWithStates_0(2, 57, 1);

                break;
        }

        return jjStartNfa_0(1, active0);
    }

    private int jjMoveStringLiteralDfa3_0(long old0, long active0)
    {
        if ((active0 &= old0) == 0L)
            return jjStartNfa_0(1, old0);

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(2, active0);

            return 3;
        }

        switch ((int)curChar) {
            case 100:
                if ((active0 & 0x4000L) != 0L)
                    return jjStartNfaWithStates_0(3, 14, 1);

                break;
            case 101:
                if ((active0 & 0x400000000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 46, 1);

                break;
            case 105:
                return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000L);
            case 108:
                if ((active0 & 0x1000000000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 48, 1);

                break;
            case 111:
                return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000L);
            case 114:
                if ((active0 & 0x400000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 34, 1);

                break;
            case 115:
                return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L);
            case 116:
                return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L);
        }

        return jjStartNfa_0(2, active0);
    }

    private int jjMoveStringLiteralDfa4_0(long old0, long active0)
    {
        if ((active0 &= old0) == 0L)
            return jjStartNfa_0(2, old0);

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(3, active0);

            return 4;
        }

        switch ((int)curChar) {
            case 97:
                return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L);
            case 101:
                if ((active0 & 0x800000000000L) != 0L)
                    return jjStartNfaWithStates_0(4, 47, 1);

                break;
            case 115:
                if ((active0 & 0x2000000000000L) != 0L)
                    return JjStopAtPos(4, 49);

                break;
            case 116:
                if ((active0 & 0x4000000000000L) != 0L)
                    return JjStopAtPos(4, 50);

                break;
        }

        return jjStartNfa_0(3, active0);
    }

    private int jjMoveStringLiteralDfa5_0(long old0, long active0)
    {
        if ((active0 &= old0) == 0L)
            return jjStartNfa_0(3, old0);

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(4, active0);

            return 5;
        }

        switch ((int)curChar) {
            case 110:
                return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L);
        }

        return jjStartNfa_0(4, active0);
    }

    private int jjMoveStringLiteralDfa6_0(long old0, long active0)
    {
        if ((active0 &= old0) == 0L)
            return jjStartNfa_0(4, old0);

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(5, active0);

            return 6;
        }

        switch ((int)curChar) {
            case 99:
                return jjMoveStringLiteralDfa7_0(active0, 0x40000000000L);
        }

        return jjStartNfa_0(5, active0);
    }

    private int jjMoveStringLiteralDfa7_0(long old0, long active0)
    {
        if ((active0 &= old0) == 0L)
            return jjStartNfa_0(5, old0);

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(6, active0);

            return 7;
        }

        switch ((int)curChar) {
            case 101:
                return jjMoveStringLiteralDfa8_0(active0, 0x40000000000L);
        }

        return jjStartNfa_0(6, active0);
    }

    private int jjMoveStringLiteralDfa8_0(long old0, long active0)
    {
        if ((active0 &= old0) == 0L)
            return jjStartNfa_0(6, old0);

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(7, active0);

            return 8;
        }

        switch ((int)curChar) {
            case 111:
                return jjMoveStringLiteralDfa9_0(active0, 0x40000000000L);
        }

        return jjStartNfa_0(7, active0);
    }

    private int jjMoveStringLiteralDfa9_0(long old0, long active0)
    {
        if ((active0 &= old0) == 0L)
            return jjStartNfa_0(7, old0);

        try {
            curChar = inputStream.ReadChar();
        } catch (IOException) {
            jjStopStringLiteralDfa_0(8, active0);

            return 9;
        }

        switch ((int)curChar) {
            case 102:
                if ((active0 & 0x40000000000L) != 0L)
                    return jjStartNfaWithStates_0(9, 42, 1);

                break;
        }

        return jjStartNfa_0(8, active0);
    }

    private void JjCheckNAdd(int state)
    {
        if (jjrounds[state] != jjround) {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }

    private void JjAddStates(int start, int end)
    {
        do {
            jjstateSet[jjnewStateCnt++] = JjnextStates[start];
        } while (start++ != end);
    }

    private void JjCheckNAddTwoStates(int state1, int state2)
    {
        JjCheckNAdd(state1);
        JjCheckNAdd(state2);
    }

    private void JjCheckNAddStates(int start, int end)
    {
        do {
            JjCheckNAdd(JjnextStates[start]);
        } while (start++ != end);
    }

    private static readonly long[] JjbitVec0 = [
        0x1ff00000fffffffeL, unchecked((long)0xffffffffffffc000L), 0xffffffffL, 0x600000000000000L
    ];

    private static readonly long[] JjbitVec2 = [
        0x0L, 0x0L, 0x0L, unchecked((long)0xff7fffffff7fffffL)
    ];

    private static readonly long[] JjbitVec3 = [
        0x0L, unchecked((long)0xffffffffffffffffL), unchecked((long)0xffffffffffffffffL),
        unchecked((long)0xffffffffffffffffL)
    ];

    private static readonly long[] JjbitVec4 = [
        unchecked((long)0xffffffffffffffffL), unchecked((long)0xffffffffffffffffL), 0xffffL, 0x0L
    ];

    private static readonly long[] JjbitVec5 = [
        unchecked((long)0xffffffffffffffffL), unchecked((long)0xffffffffffffffffL), 0x0L, 0x0L
    ];

    private static readonly long[] JjbitVec6 = [
        0x3fffffffffffL, 0x0L, 0x0L, 0x0L
    ];

    private int JjMoveNfa0(int startState, int curPos)
    {
        var startsAt = 0;
        jjnewStateCnt = 27;
        var i = 1;
        jjstateSet[0] = startState;
        var kind = 0x7fffffff;

        for (;;) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();

            if (curChar < 64) {
                var l = 1L << curChar;

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x3ff000000000000L & l) != 0L)
                                JjCheckNAddStates(0, 5);
                            else if (curChar == 46)
                                JjCheckNAdd(9);
                            else if (curChar == 36) {
                                if (kind > 64)
                                    kind = 64;
                                JjCheckNAdd(1);
                            }

                            if ((0x3fe000000000000L & l) != 0L) {
                                if (kind > 80)
                                    kind = 80;
                                JjCheckNAddTwoStates(6, 7);
                            } else if (curChar == 48) {
                                if (kind > 80)
                                    kind = 80;
                                JjCheckNAddStates(6, 8);
                            }

                            break;
                        case 1:
                            if ((0x3ff001000000000L & l) == 0L)
                                break;

                            if (kind > 64)
                                kind = 64;
                            JjCheckNAdd(1);

                            break;
                        case 3:
                            if ((0x41000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 4;

                            break;
                        case 5:
                            if ((0x3fe000000000000L & l) == 0L)
                                break;

                            if (kind > 80)
                                kind = 80;
                            JjCheckNAddTwoStates(6, 7);

                            break;
                        case 6:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;

                            if (kind > 80)
                                kind = 80;
                            JjCheckNAddTwoStates(6, 7);

                            break;
                        case 8:
                            if (curChar == 46)
                                JjCheckNAdd(9);

                            break;
                        case 9:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;

                            if (kind > 81)
                                kind = 81;
                            JjCheckNAddStates(9, 11);

                            break;
                        case 11:
                            if ((0x280000000000L & l) != 0L)
                                JjCheckNAdd(12);

                            break;
                        case 12:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;

                            if (kind > 81)
                                kind = 81;
                            JjCheckNAddTwoStates(12, 13);

                            break;
                        case 14:
                            if ((0x3ff000000000000L & l) != 0L)
                                JjCheckNAddStates(0, 5);

                            break;
                        case 15:
                            if ((0x3ff000000000000L & l) != 0L)
                                JjCheckNAddTwoStates(15, 16);

                            break;
                        case 16:
                            if (curChar != 46)
                                break;

                            if (kind > 81)
                                kind = 81;
                            JjCheckNAddStates(12, 14);

                            break;
                        case 17:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;

                            if (kind > 81)
                                kind = 81;
                            JjCheckNAddStates(12, 14);

                            break;
                        case 18:
                            if ((0x3ff000000000000L & l) != 0L)
                                JjCheckNAddTwoStates(18, 19);

                            break;
                        case 20:
                            if ((0x280000000000L & l) != 0L)
                                JjCheckNAdd(21);

                            break;
                        case 21:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;

                            if (kind > 81)
                                kind = 81;
                            JjCheckNAddTwoStates(21, 13);

                            break;
                        case 22:
                            if ((0x3ff000000000000L & l) != 0L)
                                JjCheckNAddTwoStates(22, 13);

                            break;
                        case 23:
                            if (curChar != 48)
                                break;

                            if (kind > 80)
                                kind = 80;
                            JjCheckNAddStates(6, 8);

                            break;
                        case 24:
                            if ((0xff000000000000L & l) == 0L)
                                break;

                            if (kind > 80)
                                kind = 80;
                            JjCheckNAddTwoStates(24, 7);

                            break;
                        case 26:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;

                            if (kind > 80)
                                kind = 80;
                            JjCheckNAddTwoStates(26, 7);

                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                var l = 1L << (curChar & 0x3F);

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 64)
                                    kind = 64;
                                JjCheckNAdd(1);
                            } else if (curChar == 91)
                                jjstateSet[jjnewStateCnt++] = 3;

                            break;
                        case 1:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;

                            if (kind > 64)
                                kind = 64;
                            JjCheckNAdd(1);

                            break;
                        case 2:
                            if (curChar == 91)
                                jjstateSet[jjnewStateCnt++] = 3;

                            break;
                        case 3:
                            if ((0x1000000040000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 4;

                            break;
                        case 4:
                            if (curChar == 93)
                                kind = 67;

                            break;
                        case 7:
                            if ((0x110000001100L & l) != 0L && kind > 80)
                                kind = 80;

                            break;
                        case 10:
                            if ((0x2000000020L & l) != 0L)
                                JjAddStates(15, 16);

                            break;
                        case 13:
                            if ((0x5400000054L & l) != 0L && kind > 81)
                                kind = 81;

                            break;
                        case 19:
                            if ((0x2000000020L & l) != 0L)
                                JjAddStates(17, 18);

                            break;
                        case 25:
                            if ((0x100000001000000L & l) != 0L)
                                JjCheckNAdd(26);

                            break;
                        case 26:
                            if ((0x7e0000007eL & l) == 0L)
                                break;

                            if (kind > 80)
                                kind = 80;
                            JjCheckNAddTwoStates(26, 7);

                            break;
                    }
                } while (i != startsAt);
            } else {
                var hiByte = curChar >> 8;
                var i1 = hiByte >> 6;
                var l1 = 1L << (hiByte & 0x3F);
                var i2 = (curChar & 0xff) >> 6;
                var l2 = 1L << (curChar & 0x3F);

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                        case 1:
                            if (!JjCanMove0(hiByte, i1, i2, l1, l2))
                                break;

                            if (kind > 64)
                                kind = 64;
                            JjCheckNAdd(1);

                            break;
                    }
                } while (i != startsAt);
            }

            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }

            ++curPos;

            if ((i = jjnewStateCnt) == (startsAt = 27 - (jjnewStateCnt = startsAt)))
                return curPos;

            try {
                curChar = inputStream.ReadChar();
            } catch (IOException) {
                return curPos;
            }
        }
    }

    private int jjMoveStringLiteralDfa0_2()
    {
        return (int)curChar switch {
            96 => JjStopAtPos(0, 76),
            _ => JjMoveNfa2(0, 0)
        };
    }

    private static readonly long[] JjbitVec7 = [
        unchecked((long)0xfffffffffffffffeL), unchecked((long)0xffffffffffffffffL),
        unchecked((long)0xffffffffffffffffL), unchecked((long)0xffffffffffffffffL)
    ];

    private static readonly long[] JjbitVec8 = [
        0x0L, 0x0L, unchecked((long)0xffffffffffffffffL), unchecked((long)0xffffffffffffffffL)
    ];

    private int JjMoveNfa2(int startState, int curPos)
    {
        var startsAt = 0;
        jjnewStateCnt = 6;
        var i = 1;
        jjstateSet[0] = startState;
        var kind = 0x7fffffff;

        for (;;) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();

            if (curChar < 64) {
                var l = 1L << curChar;

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if (kind > 75)
                                kind = 75;

                            break;
                        case 1:
                            if ((0x8400000000L & l) != 0L && kind > 74)
                                kind = 74;

                            break;
                        case 2:
                            if ((0xf000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 3;

                            break;
                        case 3:
                            if ((0xff000000000000L & l) == 0L)
                                break;

                            if (kind > 74)
                                kind = 74;
                            jjstateSet[jjnewStateCnt++] = 4;

                            break;
                        case 4:
                            if ((0xff000000000000L & l) != 0L && kind > 74)
                                kind = 74;

                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                var l = 1L << (curChar & 0x3F);

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0xfffffffeefffffffL & (ulong)l) != 0L) {
                                if (kind > 75)
                                    kind = 75;
                            } else if (curChar == 92)
                                JjAddStates(19, 21);

                            break;
                        case 1:
                            if ((0x14404510000000L & l) != 0L && kind > 74)
                                kind = 74;

                            break;
                        case 5:
                            if ((0xfffffffeefffffffL & (ulong)l) != 0L && kind > 75)
                                kind = 75;

                            break;
                    }
                } while (i != startsAt);
            } else {
                var hiByte = curChar >> 8;
                var i1 = hiByte >> 6;
                var l1 = 1L << (hiByte & 0x3F);
                var i2 = (curChar & 0xff) >> 6;
                var l2 = 1L << (curChar & 0x3F);

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if (JjCanMove1(hiByte, i1, i2, l1, l2) && kind > 75)
                                kind = 75;

                            break;
                    }
                } while (i != startsAt);
            }

            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }

            ++curPos;

            if ((i = jjnewStateCnt) == (startsAt = 6 - (jjnewStateCnt = startsAt)))
                return curPos;

            try {
                curChar = inputStream.ReadChar();
            } catch (IOException) {
                return curPos;
            }
        }
    }

    private int JjMoveStringLiteralDfa01()
    {
        switch ((int)curChar) {
            case 39:
                return JjStopAtPos(0, 73);
            default:
                return JjMoveNfa1(0, 0);
        }
    }

    private int JjMoveNfa1(int startState, int curPos)
    {
        var startsAt = 0;
        jjnewStateCnt = 6;
        var i = 1;
        jjstateSet[0] = startState;
        var kind = 0x7fffffff;

        for (;;) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();

            if (curChar < 64) {
                var l = 1L << curChar;

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0xffffff7fffffffffL & (ulong)l) != 0L && kind > 72)
                                kind = 72;

                            break;
                        case 1:
                            if ((0x8400000000L & l) != 0L && kind > 71)
                                kind = 71;

                            break;
                        case 2:
                            if ((0xf000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 3;

                            break;
                        case 3:
                            if ((0xff000000000000L & l) == 0L)
                                break;

                            if (kind > 71)
                                kind = 71;
                            jjstateSet[jjnewStateCnt++] = 4;

                            break;
                        case 4:
                            if ((0xff000000000000L & l) != 0L && kind > 71)
                                kind = 71;

                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                var l = 1L << (curChar & 0x3F);

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0xffffffffefffffffL & (ulong)l) != 0L) {
                                if (kind > 72)
                                    kind = 72;
                            } else if (curChar == 92)
                                JjAddStates(19, 21);

                            break;
                        case 1:
                            if ((0x14404510000000L & l) != 0L && kind > 71)
                                kind = 71;

                            break;
                        case 5:
                            if ((0xffffffffefffffffL & (ulong)l) != 0L && kind > 72)
                                kind = 72;

                            break;
                    }
                } while (i != startsAt);
            } else {
                var hiByte = curChar >> 8;
                var i1 = hiByte >> 6;
                var l1 = 1L << (hiByte & 0x3F);
                var i2 = (curChar & 0xff) >> 6;
                var l2 = 1L << (curChar & 0x3F);

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if (JjCanMove1(hiByte, i1, i2, l1, l2) && kind > 72)
                                kind = 72;

                            break;
                    }
                } while (i != startsAt);
            }

            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }

            ++curPos;

            if ((i = jjnewStateCnt) == (startsAt = 6 - (jjnewStateCnt = startsAt)))
                return curPos;

            try {
                curChar = inputStream.ReadChar();
            } catch (IOException) {
                return curPos;
            }
        }
    }

    private int JjMoveStringLiteralDfa03()
    {
        switch ((int)curChar) {
            case 34:
                return JjStopAtPos(0, 79);
            default:
                return JjMoveNfa3(0, 0);
        }
    }

    private int JjMoveNfa3(int startState, int curPos)
    {
        var startsAt = 0;
        jjnewStateCnt = 6;
        var i = 1;
        jjstateSet[0] = startState;
        var kind = 0x7fffffff;

        for (;;) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();

            if (curChar < 64) {
                var l = 1L << curChar;

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0xfffffffbffffffffL & (ulong)l) != 0L && kind > 78)
                                kind = 78;

                            break;
                        case 1:
                            if ((0x8400000000L & l) != 0L && kind > 77)
                                kind = 77;

                            break;
                        case 2:
                            if ((0xf000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 3;

                            break;
                        case 3:
                            if ((0xff000000000000L & l) == 0L)
                                break;

                            if (kind > 77)
                                kind = 77;
                            jjstateSet[jjnewStateCnt++] = 4;

                            break;
                        case 4:
                            if ((0xff000000000000L & l) != 0L && kind > 77)
                                kind = 77;

                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                var l = 1L << (curChar & 0x3F);

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0xffffffffefffffffL & (ulong)l) != 0L) {
                                if (kind > 78)
                                    kind = 78;
                            } else if (curChar == 92)
                                JjAddStates(19, 21);

                            break;
                        case 1:
                            if ((0x14404510000000L & l) != 0L && kind > 77)
                                kind = 77;

                            break;
                        case 5:
                            if ((0xffffffffefffffffL & (ulong)l) != 0L && kind > 78)
                                kind = 78;

                            break;
                    }
                } while (i != startsAt);
            } else {
                var hiByte = curChar >> 8;
                var i1 = hiByte >> 6;
                var l1 = 1L << (hiByte & 0x3F);
                var i2 = (curChar & 0xff) >> 6;
                var l2 = 1L << (curChar & 0x3F);

                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if (JjCanMove1(hiByte, i1, i2, l1, l2) && kind > 78)
                                kind = 78;

                            break;
                    }
                } while (i != startsAt);
            }

            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }

            ++curPos;

            if ((i = jjnewStateCnt) == (startsAt = 6 - (jjnewStateCnt = startsAt)))
                return curPos;

            try {
                curChar = inputStream.ReadChar();
            } catch (IOException) {
                return curPos;
            }
        }
    }

    private static readonly int[] JjnextStates = [
        15, 16, 18, 19, 22, 13, 24, 25, 7, 9, 10, 13, 17, 10, 13, 11,
        12, 20, 21, 1, 2, 3
    ];

    private static bool JjCanMove0(int hiByte, int i1, int i2, long l1, long l2)
    {
        switch (hiByte) {
            case 0:
                return (JjbitVec2[i2] & l2) != 0L;
            case 48:
                return (JjbitVec3[i2] & l2) != 0L;
            case 49:
                return (JjbitVec4[i2] & l2) != 0L;
            case 51:
                return (JjbitVec5[i2] & l2) != 0L;
            case 61:
                return (JjbitVec6[i2] & l2) != 0L;
            default:
                if ((JjbitVec0[i1] & l1) != 0L)
                    return true;

                return false;
        }
    }

    private static bool JjCanMove1(int hiByte, int i1, int i2, long l1, long l2)
    {
        switch (hiByte) {
            case 0:
                return (JjbitVec8[i2] & l2) != 0L;
            default:
                if ((JjbitVec7[i1] & l1) != 0L)
                    return true;

                return false;
        }
    }

    private static readonly string?[] JjstrLiteralImages = [
        /* // TODO: string escape.
         "", "\54", "\75", "\77", "\72", "\174\174", "\157\162", "\46\46",
        "\141\156\144", "\174", "\142\157\162", "\136", "\170\157\162", "\46", "\142\141\156\144",
        "\75\75", "\145\161", "\41\75", "\156\145\161", "\74", "\154\164", "\76", "\147\164",
        "\74\75", "\154\164\145", "\76\75", "\147\164\145", "\151\156", "\156\157\164",
        "\74\74", "\163\150\154", "\76\76", "\163\150\162", "\76\76\76", "\165\163\150\162",
        "\53", "\55", "\52", "\57", "\45", "\176", "\41",
        "\151\156\163\164\141\156\143\145\157\146", "\56", "\50", "\51", "\164\162\165\145", "\146\141\154\163\145",
        "\156\165\154\154", "\43\164\150\151\163", "\43\162\157\157\164", "\43", "\133", "\135", "\173",
        "\175", "\100", "\156\145\167", "\44", null, null, null, null, null, null, null, null,
        */
        "", "\x2c", "\x3d", "\x3f", "\x3a", "\x7c\x7c", "\x6f\x72", "\x26\x26",
        "\x61\x6e\x64", "\x7c", "\x62\x6f\x72", "\x5e", "\x78\x6f\x72", "\x26", "\x62\x61\x6e\x64", "\x3d\x3d",
        "\x65\x71", "\x21\x3d", "\x6e\x65\x71", "\x3c", "\x6c\x74", "\x3e", "\x67\x74", "\x3c\x3d",
        "\x6c\x74\x65", "\x3e\x3d", "\x67\x74\x65", "\x69\x6e", "\x6e\x6f\x74", "\x3c\x3c", "\x73\x68\x6c", "\x3e\x3e",
        "\x73\x68\x72", "\x3e\x3e\x3e", "\x75\x73\x68\x72", "\x2b", "\x2d", "\x2a", "\x2f", "\x25",
        "\x7e", "\x21", "\x69\x6e\x73\x74\x61\x6e\x63\x65\x6f\x66", "\x2e", "\x28", "\x29", "\x74\x72\x75\x65",
        "\x66\x61\x6c\x73\x65",
        "\x6e\x75\x6c\x6c", "\x23\x74\x68\x69\x73", "\x23\x72\x6f\x6f\x74", "\x23", "\x5b", "\x5d", "\x7b", "\x7d",
        "\x40", "\x6e\x65\x77", "\x24", null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null
    ];

    private static readonly int[] JjnewLexState = [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, 1, 3, -1, -1, 0, -1,
        -1, 0, -1, -1, 0, -1, -1, -1, -1, -1, -1
    ];

    private static readonly long[] JjtoToken = [
        0x7ffffffffffffffL, 0x39209L
    ];

    private static readonly long[] JjtoSkip = [
        unchecked((long)0xf800000000000000L), 0x0L
    ];

    private JavaCharStream inputStream = stream;

    private readonly int[] jjrounds = new int[27];

    private readonly int[] jjstateSet = new int[54];

    private StringBuilder? image;

    private int jjimageLen;

    private char curChar;

    public void ReInit(JavaCharStream stream)
    {
        jjmatchedPos = jjnewStateCnt = 0;
        curLexState = defaultLexState;
        inputStream = stream;
        ReInitRounds();
    }

    private void ReInitRounds()
    {
        int i;
        jjround = unchecked((int)0x80000001);
        for (i = 27; i-- > 0;)
            jjrounds[i] = unchecked((int)0x80000000);
    }

    private Token JjFillToken()
    {
        var t = Token.NewToken(jjmatchedKind);
        var im = JjstrLiteralImages[jjmatchedKind];
        t.Image = im == null ? inputStream.GetImage() : im;
        t.BeginLine = inputStream.GetBeginLine();
        t.BeginColumn = inputStream.GetBeginColumn();
        inputStream.GetEndLine();
        inputStream.GetEndColumn();

        return t;
    }

    private int curLexState = 0;

    private readonly int defaultLexState = 0;

    private int jjnewStateCnt;

    private int jjround;

    private int jjmatchedPos;

    private int jjmatchedKind;

    public Token GetNextToken()
    {
        Token matchedToken;
        var curPos = 0;

        EOFLoop :

        for (;;) {
            try {
                curChar = inputStream.BeginToken();
            } catch (IOException) {
                jjmatchedKind = 0;
                matchedToken = JjFillToken();

                return matchedToken;
            }

            image = null;
            jjimageLen = 0;

            for (;;) {
                switch (curLexState) {
                    case 0:
                        try {
                            inputStream.Backup(0);
                            while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
                                curChar = inputStream.BeginToken();
                        } catch (IOException) {
                            goto EOFLoop;
                        }

                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_0();

                        break;
                    case 1:
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = JjMoveStringLiteralDfa01();

                        break;
                    case 2:
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_2();

                        break;
                    case 3:
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = JjMoveStringLiteralDfa03();

                        break;
                }

                if (jjmatchedKind != 0x7fffffff) {
                    if (jjmatchedPos + 1 < curPos)
                        inputStream.Backup(curPos - jjmatchedPos - 1);

                    if ((JjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 0x3F))) != 0L) {
                        matchedToken = JjFillToken();
                        TokenLexicalActions();
                        if (JjnewLexState[jjmatchedKind] != -1)
                            curLexState = JjnewLexState[jjmatchedKind];

                        return matchedToken;
                    } else if ((JjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 0x3F))) != 0L) {
                        if (JjnewLexState[jjmatchedKind] != -1)
                            curLexState = JjnewLexState[jjmatchedKind];

                        goto EOFLoop;
                    }

                    MoreLexicalActions();
                    if (JjnewLexState[jjmatchedKind] != -1)
                        curLexState = JjnewLexState[jjmatchedKind];
                    curPos = 0;
                    jjmatchedKind = 0x7fffffff;

                    try {
                        curChar = inputStream.ReadChar();

                        continue;
                    } catch (IOException) {
                    }
                }

                var errorLine = inputStream.GetEndLine();
                var errorColumn = inputStream.GetEndColumn();
                string? errorAfter = null;
                var eofSeen = false;

                try {
                    inputStream.ReadChar();
                    inputStream.Backup(1);
                } catch (IOException) {
                    eofSeen = true;
                    errorAfter = curPos <= 1 ? "" : inputStream.GetImage();

                    if (curChar == '\n' || curChar == '\r') {
                        errorLine++;
                        errorColumn = 0;
                    } else
                        errorColumn++;
                }

                if (!eofSeen) {
                    inputStream.Backup(1);
                    errorAfter = curPos <= 1 ? "" : inputStream.GetImage();
                }

                throw new TokenMgrError(eofSeen, errorLine, errorColumn, errorAfter, curChar);
            }
        }
    }

    void MoreLexicalActions()
    {
        jjimageLen += jjmatchedPos + 1;

        switch (jjmatchedKind) {
            case 69:
            case 70:
                if (image == null)
                    image = new StringBuilder(new string(inputStream.GetSuffix(jjimageLen)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen));
                jjimageLen = 0;
                stringBuffer = new StringBuilder();

                break;
            case 71:
                if (image == null)
                    image = new StringBuilder(new string(inputStream.GetSuffix(jjimageLen)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen));
                jjimageLen = 0;
                charValue = EscapeChar();
                stringBuffer.Append(charValue);

                break;
            case 72:
                if (image == null)
                    image = new StringBuilder(new string(inputStream.GetSuffix(jjimageLen)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen));
                jjimageLen = 0;
                charValue = image[image.Length - 1];
                stringBuffer.Append(charValue);

                break;
            case 74:
                if (image == null)
                    image = new StringBuilder(new string(inputStream.GetSuffix(jjimageLen)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen));
                jjimageLen = 0;
                charValue = EscapeChar();

                break;
            case 75:
                if (image == null)
                    image = new StringBuilder(new string(inputStream.GetSuffix(jjimageLen)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen));
                jjimageLen = 0;
                charValue = image[image.Length - 1];

                break;
            case 77:
                if (image == null)
                    image = new StringBuilder(new string(inputStream.GetSuffix(jjimageLen)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen));
                jjimageLen = 0;
                stringBuffer.Append(EscapeChar());

                break;
            case 78:
                if (image == null)
                    image = new StringBuilder(new string(inputStream.GetSuffix(jjimageLen)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen));
                jjimageLen = 0;
                stringBuffer.Append(image[image.Length - 1]);

                break;
        }
    }

    private void TokenLexicalActions()
    {
        switch (jjmatchedKind) {
            case 67:
                if (image == null)
                    image = new StringBuilder(
                        new string(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1));

                literalValue = image[1] switch {
                    '^' => OGNL.DynamicSubscript.First,
                    '|' => OGNL.DynamicSubscript.Mid,
                    '$' => OGNL.DynamicSubscript.Last,
                    '*' => OGNL.DynamicSubscript.All,
                    _ => literalValue
                };

                break;
            case 73:
                if (image == null)
                    image = new StringBuilder(
                        new string(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1));

                if (stringBuffer.Length == 1) {
                    literalValue = charValue;
                } else {
                    literalValue = stringBuffer.ToString();
                }

                break;
            case 76:
                if (image == null)
                    image = new StringBuilder(
                        new string(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1));
                literalValue = charValue;

                break;
            case 79:
                if (image == null)
                    image = new StringBuilder(
                        new string(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1));
                literalValue = stringBuffer.ToString();

                break;
            case 80:
                if (image == null)
                    image = new StringBuilder(
                        new string(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1));
                literalValue =
                    MakeInt();

                break;
            case 81:
                if (image == null)
                    image = new StringBuilder(
                        new string(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1)));
                else
                    image.Append(inputStream.GetSuffix(jjimageLen + jjmatchedPos + 1));
                literalValue = MakeFloat();

                break;
        }
    }
}
