/* Generated By:JJTree: Do not edit this line. JJTOgnlParserState.java */

namespace OGNL.Parser;

internal class ParserState {
    private readonly Stack<Node> nodes = new();

    private readonly Stack<int> marks = new();

    private int sp; // number of nodes on stack

    private int mk; // current mark

    /* Returns the root node of the AST.  It only makes sense to call
       this after a successful parse. */
    public Node RootNode()
    {
        return nodes.Peek();
    }

    /* Pushes a node on to the stack. */
    private void PushNode(Node n)
    {
        nodes.Push(n);
        ++sp;
    }

    /* Returns the node on the top of the stack, and remove it from the
       stack.  */
    internal Node PopNode()
    {
        if (--sp < mk)
            mk = marks.Pop();

        return nodes.Pop();
    }

    /* Returns the number of children on the stack in the current node
       scope. */
    private int NodeArity()
    {
        return sp - mk;
    }

    internal void ClearNodeScope()
    {
        while (sp > mk) {
            PopNode();
        }

        mk = marks.Pop();
    }

    internal void OpenNodeScope(Node n)
    {
        marks.Push(mk);
        mk = sp;
        n.Open();
    }

    /* A definite node is constructed from a specified number of
       children.  That number of nodes are popped from the stack and
       made the children of the definite node.  Then the definite node
       is pushed on to the stack. */
    internal void CloseNodeScope(Node n, int num)
    {
        mk = marks.Pop();

        while (num-- > 0) {
            var c = PopNode();
            c.SetParent(n);
            n.AddChild(c, num);
        }

        n.Close();
        PushNode(n);
    }

    /* A conditional node is constructed if its condition is true.  All
       the nodes that have been pushed since the node was opened are
       made children of the the conditional node, which is then pushed
       on to the stack.  If the condition is false the node is not
       constructed and they are left on the stack. */
    internal void CloseNodeScope(Node n, bool condition)
    {
        if (condition) {
            var a = NodeArity();
            mk = marks.Pop();

            while (a-- > 0) {
                var c = PopNode();
                c.SetParent(n);
                n.AddChild(c, a);
            }

            n.Close();
            PushNode(n);
        } else
            mk = marks.Pop();
    }
}
