using System.Collections;
using System.Text;
using static OGNL.Parser.ParserConstants;
using static OGNL.Parser.ParserTreeConstants;

/* Generated By:JJTree&JavaCC: Do not edit this line. OgnlParser.java */
namespace OGNL.Parser;

/**
 * OgnlParser is a JavaCC parser class; it translates OGNL expressions into abstract
 * syntax trees (ASTs) that can then be interpreted by the getValue and setValue methods.
 */
internal class Parser /*@bgen(jjtree)*/ {
    private readonly ParserState jjtree = new();

    /**
     * This is the top-level construct of OGNL.
     */
    public Node TopLevelExpression()
    {
        Expression();
        jj_consume_token(0);

        return jjtree.RootNode();
    }

    // sequence (level 14)
    private void Expression()
    {
        AssignmentExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 1:
                    break;
                default:
                    jjLa1[0] = jjGen;

                    return;
            }

            jj_consume_token(1);
            var jjtn001 = new AstSequence(JjtSequence);
            var jjtc001 = true;
            jjtree.OpenNodeScope(jjtn001);

            try {
                AssignmentExpression();
            } catch (Exception) {
                if (jjtc001) {
                    jjtree.ClearNodeScope();
                    jjtc001 = false;
                } else
                    jjtree.PopNode();

                throw;
            } finally {
                if (jjtc001)
                    jjtree.CloseNodeScope(jjtn001, 2);
            }
        }
    }

    // assignment expression (level 13)
    private void AssignmentExpression()
    {
        ConditionalTestExpression();

        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
            case 2:
                jj_consume_token(2);
                var jjtn001 = new AstAssign(JjtAssign);
                var jjtc001 = true;
                jjtree.OpenNodeScope(jjtn001);

                try {
                    AssignmentExpression();
                } catch (Exception) {
                    if (jjtc001) {
                        jjtree.ClearNodeScope();
                        jjtc001 = false;
                    } else
                        jjtree.PopNode();

                    throw;
                } finally {
                    if (jjtc001)
                        jjtree.CloseNodeScope(jjtn001, 2);
                }

                break;
            default:
                jjLa1[1] = jjGen;

                break;
        }
    }

    // conditional test (level 12)
    private void ConditionalTestExpression()
    {
        LogicalOrExpression();

        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
            case 3:
                jj_consume_token(3);
                ConditionalTestExpression();
                jj_consume_token(4);
                var jjtn001 = new AstTest(JjtTest);
                var jjtc001 = true;
                jjtree.OpenNodeScope(jjtn001);

                try {
                    ConditionalTestExpression();
                } catch (Exception) {
                    if (jjtc001) {
                        jjtree.ClearNodeScope();
                        jjtc001 = false;
                    } else
                        jjtree.PopNode();

                    throw;
                } finally {
                    if (jjtc001)
                        jjtree.CloseNodeScope(jjtn001, 3);
                }

                break;
            default:
                jjLa1[2] = jjGen;

                break;
        }
    }

    // logical or (||)  (level 11)
    private void LogicalOrExpression()
    {
        LogicalAndExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 5:
                case 6:
                    break;
                default:
                    jjLa1[3] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 5:
                    jj_consume_token(5);

                    break;
                case 6:
                    jj_consume_token(6);

                    break;
                default:
                    jjLa1[4] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }

            var jjtn001 = new AstOr(JjtOr);
            var jjtc001 = true;
            jjtree.OpenNodeScope(jjtn001);

            try {
                LogicalAndExpression();
            } catch (Exception) {
                if (jjtc001) {
                    jjtree.ClearNodeScope();
                    jjtc001 = false;
                } else
                    jjtree.PopNode();

                throw;
            } finally {
                if (jjtc001)
                    jjtree.CloseNodeScope(jjtn001, 2);
            }
        }
    }

    // logical and (&&)  (level 10)
    private void LogicalAndExpression()
    {
        InclusiveOrExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 7:
                case 8:
                    break;
                default:
                    jjLa1[5] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 7:
                    jj_consume_token(7);

                    break;
                case 8:
                    jj_consume_token(8);

                    break;
                default:
                    jjLa1[6] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }

            var jjtn001 = new AstAnd(JjtAnd);
            var jjtc001 = true;
            jjtree.OpenNodeScope(jjtn001);

            try {
                InclusiveOrExpression();
            } catch (Exception) {
                if (jjtc001) {
                    jjtree.ClearNodeScope();
                    jjtc001 = false;
                } else
                    jjtree.PopNode();

                throw;
            } finally {
                if (jjtc001)
                    jjtree.CloseNodeScope(jjtn001, 2);
            }
        }
    }

    // bitwise or non-short-circuiting or (|)  (level 9)
    private void InclusiveOrExpression()
    {
        ExclusiveOrExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 9:
                case 10:
                    break;
                default:
                    jjLa1[7] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 9:
                    jj_consume_token(9);

                    break;
                case 10:
                    jj_consume_token(10);

                    break;
                default:
                    jjLa1[8] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }

            var jjtn001 = new AstBitOr(JjtBitOr);
            var jjtc001 = true;
            jjtree.OpenNodeScope(jjtn001);

            try {
                ExclusiveOrExpression();
            } catch (Exception) {
                if (jjtc001) {
                    jjtree.ClearNodeScope();
                    jjtc001 = false;
                } else
                    jjtree.PopNode();

                throw;
            } finally {
                if (jjtc001)
                    jjtree.CloseNodeScope(jjtn001, 2);
            }
        }
    }

    // exclusive or (^)  (level 8)
    private void ExclusiveOrExpression()
    {
        AndExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 11:
                case 12:

                    break;
                default:
                    jjLa1[9] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 11:
                    jj_consume_token(11);

                    break;
                case 12:
                    jj_consume_token(12);

                    break;
                default:
                    jjLa1[10] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }

            var jjtn001 = new AstXor(JjtXor);
            var jjtc001 = true;
            jjtree.OpenNodeScope(jjtn001);

            try {
                AndExpression();
            } catch (Exception) {
                if (jjtc001) {
                    jjtree.ClearNodeScope();
                    jjtc001 = false;
                } else
                    jjtree.PopNode();

                throw;
            } finally {
                if (jjtc001)
                    jjtree.CloseNodeScope(jjtn001, 2);
            }
        }
    }

    // bitwise or non-short-circuiting and (&)  (level 7)
    private void AndExpression()
    {
        EqualityExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 13:
                case 14:

                    break;
                default:
                    jjLa1[11] = jjGen;

                    return; // goto label_6;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 13:
                    jj_consume_token(13);

                    break;
                case 14:
                    jj_consume_token(14);

                    break;
                default:
                    jjLa1[12] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }

            var jjtn001 = new AstBitAnd(JjtBitAnd);
            var jjtc001 = true;
            jjtree.OpenNodeScope(jjtn001);

            try {
                EqualityExpression();
            } catch (Exception) {
                if (jjtc001) {
                    jjtree.ClearNodeScope();
                    jjtc001 = false;
                } else
                    jjtree.PopNode();

                throw;
            } finally {
                if (jjtc001)
                    jjtree.CloseNodeScope(jjtn001, 2);
            }
        }
    }

    // equality/inequality (==/!=) (level 6)
    private void EqualityExpression()
    {
        RelationalExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 15:
                case 16:
                case 17:
                case 18:
                    break;
                default:
                    jjLa1[13] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 15:
                case 16:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 15:
                            jj_consume_token(15);

                            break;
                        case 16:
                            jj_consume_token(16);

                            break;
                        default:
                            jjLa1[14] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn001 = new AstEq(JjtEq);
                    var jjtc001 = true;
                    jjtree.OpenNodeScope(jjtn001);

                    try {
                        RelationalExpression();
                    } catch (Exception) {
                        if (jjtc001) {
                            jjtree.ClearNodeScope();
                            jjtc001 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc001)
                            jjtree.CloseNodeScope(jjtn001, 2);
                    }

                    break;
                case 17:
                case 18:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 17:
                            jj_consume_token(17);

                            break;
                        case 18:
                            jj_consume_token(18);

                            break;
                        default:
                            jjLa1[15] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn002 = new AstNotEq(JjtNotEq);
                    var jjtc002 = true;
                    jjtree.OpenNodeScope(jjtn002);

                    try {
                        RelationalExpression();
                    } catch (Exception) {
                        if (jjtc002) {
                            jjtree.ClearNodeScope();
                            jjtc002 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc002)
                            jjtree.CloseNodeScope(jjtn002, 2);
                    }

                    break;
                default:
                    jjLa1[16] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }
        }
    }

    // bool relational expressions (level 5)
    private void RelationalExpression()
    {
        ShiftExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 19:
                case 20:
                case 21:
                case 22:
                case 23:
                case 24:
                case 25:
                case 26:
                case 27:
                case 28:
                    break;
                default:
                    jjLa1[17] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 19:
                case 20:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 19:
                            jj_consume_token(19);

                            break;
                        case 20:
                            jj_consume_token(20);

                            break;
                        default:
                            jjLa1[18] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn001 = new AstLess(JjtLess);
                    var jjtc001 = true;
                    jjtree.OpenNodeScope(jjtn001);

                    try {
                        ShiftExpression();
                    } catch (Exception) {
                        if (jjtc001) {
                            jjtree.ClearNodeScope();
                            jjtc001 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc001)
                            jjtree.CloseNodeScope(jjtn001, 2);
                    }

                    break;
                case 21:
                case 22:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 21:
                            jj_consume_token(21);

                            break;
                        case 22:
                            jj_consume_token(22);

                            break;
                        default:
                            jjLa1[19] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn002 = new AstGreater(JjtGreater);
                    var jjtc002 = true;
                    jjtree.OpenNodeScope(jjtn002);

                    try {
                        ShiftExpression();
                    } catch (Exception) {
                        if (jjtc002) {
                            jjtree.ClearNodeScope();
                            jjtc002 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc002)
                            jjtree.CloseNodeScope(jjtn002, 2);
                    }

                    break;
                case 23:
                case 24:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 23:
                            jj_consume_token(23);

                            break;
                        case 24:
                            jj_consume_token(24);

                            break;
                        default:
                            jjLa1[20] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn003 = new AstLessEq(JjtLessEq);
                    var jjtc003 = true;
                    jjtree.OpenNodeScope(jjtn003);

                    try {
                        ShiftExpression();
                    } catch (Exception) {
                        if (jjtc003) {
                            jjtree.ClearNodeScope();
                            jjtc003 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc003)
                            jjtree.CloseNodeScope(jjtn003, 2);
                    }

                    break;
                case 25:
                case 26:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 25:
                            jj_consume_token(25);

                            break;
                        case 26:
                            jj_consume_token(26);

                            break;
                        default:
                            jjLa1[21] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn004 = new AstGreaterEq(JjtGreaterEq);
                    var jjtc004 = true;
                    jjtree.OpenNodeScope(jjtn004);

                    try {
                        ShiftExpression();
                    } catch (Exception) {
                        if (jjtc004) {
                            jjtree.ClearNodeScope();
                            jjtc004 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc004)
                            jjtree.CloseNodeScope(jjtn004, 2);
                    }

                    break;
                case 27:
                    jj_consume_token(27);
                    var jjtn005 = new AstIn(JjtIn);
                    var jjtc005 = true;
                    jjtree.OpenNodeScope(jjtn005);

                    try {
                        ShiftExpression();
                    } catch (Exception) {
                        if (jjtc005) {
                            jjtree.ClearNodeScope();
                            jjtc005 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc005)
                            jjtree.CloseNodeScope(jjtn005, 2);
                    }

                    break;
                case 28:
                    jj_consume_token(28);
                    jj_consume_token(27);
                    var jjtn006 = new AstNotIn(JjtNotIn);
                    var jjtc006 = true;
                    jjtree.OpenNodeScope(jjtn006);

                    try {
                        ShiftExpression();
                    } catch (Exception) {
                        if (jjtc006) {
                            jjtree.ClearNodeScope();
                            jjtc006 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc006)
                            jjtree.CloseNodeScope(jjtn006, 2);
                    }

                    break;
                default:
                    jjLa1[22] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }
        }
    }

    // bit shift expressions (level 4)
    private void ShiftExpression()
    {
        AdditiveExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 29:
                case 30:
                case 31:
                case 32:
                case 33:
                case 34:
                    break;
                default:
                    jjLa1[23] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 29:
                case 30:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 29:
                            jj_consume_token(29);

                            break;
                        case 30:
                            jj_consume_token(30);

                            break;
                        default:
                            jjLa1[24] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn001 = new AstShiftLeft(JjtShiftLeft);
                    var jjtc001 = true;
                    jjtree.OpenNodeScope(jjtn001);

                    try {
                        AdditiveExpression();
                    } catch (Exception) {
                        if (jjtc001) {
                            jjtree.ClearNodeScope();
                            jjtc001 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc001)
                            jjtree.CloseNodeScope(jjtn001, 2);
                    }

                    break;
                case 31:
                case 32:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 31:
                            jj_consume_token(31);

                            break;
                        case 32:
                            jj_consume_token(32);

                            break;
                        default:
                            jjLa1[25] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn002 = new AstShiftRight(JjtShiftRight);
                    var jjtc002 = true;
                    jjtree.OpenNodeScope(jjtn002);

                    try {
                        AdditiveExpression();
                    } catch (Exception) {
                        if (jjtc002) {
                            jjtree.ClearNodeScope();
                            jjtc002 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc002)
                            jjtree.CloseNodeScope(jjtn002, 2);
                    }

                    break;
                case 33:
                case 34:
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 33:
                            jj_consume_token(33);

                            break;
                        case 34:
                            jj_consume_token(34);

                            break;
                        default:
                            jjLa1[26] = jjGen;
                            jj_consume_token(-1);

                            throw new ParseException();
                    }

                    var jjtn003 = new AstUnsignedShiftRight(JjtUnsignedShiftRight);
                    var jjtc003 = true;
                    jjtree.OpenNodeScope(jjtn003);

                    try {
                        AdditiveExpression();
                    } catch (Exception) {
                        if (jjtc003) {
                            jjtree.ClearNodeScope();
                            jjtc003 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc003)
                            jjtree.CloseNodeScope(jjtn003, 2);
                    }

                    break;
                default:
                    jjLa1[27] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }
        }
    }

    // binary addition/subtraction (level 3)
    private void AdditiveExpression()
    {
        MultiplicativeExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 35:
                case 36:
                    break;
                default:
                    jjLa1[28] = jjGen;

                    return; // goto label_10;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 35:
                    jj_consume_token(35);
                    var jjtn001 = new AstAdd(JjtAdd);
                    var jjtc001 = true;
                    jjtree.OpenNodeScope(jjtn001);

                    try {
                        MultiplicativeExpression();
                    } catch (Exception) {
                        if (jjtc001) {
                            jjtree.ClearNodeScope();
                            jjtc001 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc001)
                            jjtree.CloseNodeScope(jjtn001, 2);
                    }

                    break;
                case 36:
                    jj_consume_token(36);
                    var jjtn002 = new AstSubtract(JjtSubtract);
                    var jjtc002 = true;
                    jjtree.OpenNodeScope(jjtn002);

                    try {
                        MultiplicativeExpression();
                    } catch (Exception) {
                        if (jjtc002) {
                            jjtree.ClearNodeScope();
                            jjtc002 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc002)
                            jjtree.CloseNodeScope(jjtn002, 2);
                    }

                    break;
                default:
                    jjLa1[29] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }
        }
    }

    // multiplication/division/remainder (level 2)
    private void MultiplicativeExpression()
    {
        UnaryExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 37:
                case 38:
                case 39:
                    break;
                default:
                    jjLa1[30] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 37:
                    jj_consume_token(37);
                    var jjtn001 = new AstMultiply(JjtMultiply);
                    var jjtc001 = true;
                    jjtree.OpenNodeScope(jjtn001);

                    try {
                        UnaryExpression();
                    } catch (Exception) {
                        if (jjtc001) {
                            jjtree.ClearNodeScope();
                            jjtc001 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc001)
                            jjtree.CloseNodeScope(jjtn001, 2);
                    }

                    break;
                case 38:
                    jj_consume_token(38);
                    var jjtn002 = new AstDivide(JjtDivide);
                    var jjtc002 = true;
                    jjtree.OpenNodeScope(jjtn002);

                    try {
                        UnaryExpression();
                    } catch (Exception) {
                        if (jjtc002) {
                            jjtree.ClearNodeScope();
                            jjtc002 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc002)
                            jjtree.CloseNodeScope(jjtn002, 2);
                    }

                    break;
                case 39:
                    jj_consume_token(39);
                    var jjtn003 = new AstRemainder(JjtRemainder);
                    var jjtc003 = true;
                    jjtree.OpenNodeScope(jjtn003);

                    try {
                        UnaryExpression();
                    } catch (Exception) {
                        if (jjtc003) {
                            jjtree.ClearNodeScope();
                            jjtc003 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc003)
                            jjtree.CloseNodeScope(jjtn003, 2);
                    }

                    break;
                default:
                    jjLa1[31] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }
        }
    }

    // unary (level 1)
    private void UnaryExpression()
    {
        StringBuilder sb;
        Token t;
        AstInstanceof ionode;

        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
            case 36:
                jj_consume_token(36);
                var jjtn001 = new AstNegate(JjtNegate);
                var jjtc001 = true;
                jjtree.OpenNodeScope(jjtn001);

                try {
                    UnaryExpression();
                } catch (Exception) {
                    if (jjtc001) {
                        jjtree.ClearNodeScope();
                        jjtc001 = false;
                    } else
                        jjtree.PopNode();

                    throw;
                } finally {
                    if (jjtc001)
                        jjtree.CloseNodeScope(jjtn001, 1);
                }

                break;
            case 35:
                jj_consume_token(35);
                UnaryExpression();

                break;
            case 40:
                jj_consume_token(40);
                var jjtn002 = new AstBitNegate(JjtBitNegate);
                var jjtc002 = true;
                jjtree.OpenNodeScope(jjtn002);

                try {
                    UnaryExpression();
                } catch (Exception) {
                    if (jjtc002) {
                        jjtree.ClearNodeScope();
                        jjtc002 = false;
                    } else
                        jjtree.PopNode();

                    throw;
                } finally {
                    if (jjtc002)
                        jjtree.CloseNodeScope(jjtn002, 1);
                }

                break;
            case 28:
            case 41:
                switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                    case 41:
                        jj_consume_token(41);

                        break;
                    case 28:
                        jj_consume_token(28);

                        break;
                    default:
                        jjLa1[32] = jjGen;
                        jj_consume_token(-1);

                        throw new ParseException();
                }

                var jjtn003 = new AstNot(JjtNot);
                var jjtc003 = true;
                jjtree.OpenNodeScope(jjtn003);

                try {
                    UnaryExpression();
                } catch (Exception) {
                    if (jjtc003) {
                        jjtree.ClearNodeScope();
                        jjtc003 = false;
                    } else
                        jjtree.PopNode();

                    throw;
                } finally {
                    if (jjtc003)
                        jjtree.CloseNodeScope(jjtn003, 1);
                }

                break;
            case 4:
            case 44:
            case 46:
            case 47:
            case 48:
            case 49:
            case 50:
            case 51:
            case 52:
            case 54:
            case 56:
            case 57:
            case Ident:
            case DynamicSub:
            case CharLiteral:
            case BackCharLiteral:
            case StringLiteral:
            case IntLiteral:
            case FltLiteral:
                NavigationChain();

                switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                    case 42:
                        jj_consume_token(42);
                        t = jj_consume_token(Ident);

                        var jjtn004 = new AstInstanceof(JjtInstanceOf);
                        var jjtc004 = true;

                        jjtree.OpenNodeScope(jjtn004);

                        try {
                            jjtree.CloseNodeScope(jjtn004, 1);
                            jjtc004 = false;
                            sb = new StringBuilder(t.Image);
                            ionode = jjtn004;
                        } finally {
                            if (jjtc004)
                                jjtree.CloseNodeScope(jjtn004, 1);
                        }

                        // label_12: // move to end of loop.
                        while (true) {
                            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                case 43:

                                    break;
                                default:
                                    jjLa1[33] = jjGen;

                                    goto label_12;
                            }

                            jj_consume_token(43);
                            t = jj_consume_token(Ident);
                            sb.Append('.').Append(t.Image);
                        }

                        label_12:
                        ionode.TargetType = sb.ToString();

                        break;
                    default:
                        jjLa1[34] = jjGen;

                        break;
                }

                break;
            default:
                jjLa1[35] = jjGen;
                jj_consume_token(-1);

                throw new ParseException();
        }
    }

    // navigation chain: property references, method calls, projections, selections, etc.
    private void NavigationChain()
    {
        PrimaryExpression();

        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 43:
                case 44:
                case 52:
                case DynamicSub:
                    break;
                default:
                    jjLa1[36] = jjGen;

                    return;
            }

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 43:
                    jj_consume_token(43);
                    var jjtn001 = new AstChain(JjtChain);
                    var jjtc001 = true;
                    jjtree.OpenNodeScope(jjtn001);

                    try {
                        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                            case Ident:
                                if (jj_2_1(2)) {
                                    MethodCall();
                                } else {
                                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                        case Ident:
                                            PropertyName();

                                            break;
                                        default:
                                            jjLa1[37] = jjGen;
                                            jj_consume_token(-1);

                                            throw new ParseException();
                                    }
                                }

                                break;
                            case 54:
                                if (jj_2_2(2)) {
                                    Projection();
                                } else {
                                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                        case 54:
                                            Selection();

                                            break;
                                        default:
                                            jjLa1[38] = jjGen;
                                            jj_consume_token(-1);

                                            throw new ParseException();
                                    }
                                }

                                break;
                            case 44:
                                jj_consume_token(44);
                                Expression();
                                jj_consume_token(45);

                                break;
                            default:
                                jjLa1[39] = jjGen;
                                jj_consume_token(-1);

                                throw new ParseException();
                        }
                    } catch (Exception) {
                        if (jjtc001) {
                            jjtree.ClearNodeScope();
                            jjtc001 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc001)
                            jjtree.CloseNodeScope(jjtn001, 2);
                    }

                    break;
                case 52:
                case DynamicSub:
                    var jjtn002 = new AstChain(JjtChain);
                    var jjtc002 = true;

                    jjtree.OpenNodeScope(jjtn002);

                    try {
                        Index();
                    } catch (Exception) {
                        if (jjtc002) {
                            jjtree.ClearNodeScope();
                            jjtc002 = false;
                        } else
                            jjtree.PopNode();

                        throw;
                    } finally {
                        if (jjtc002)
                            jjtree.CloseNodeScope(jjtn002, 2);
                    }

                    break;
                case 44:
                    jj_consume_token(44);
                    Expression();

                    var jjtn003 = new AstEval(JjtEval);
                    var jjtc003 = true;

                    jjtree.OpenNodeScope(jjtn003);

                    try {
                        jj_consume_token(45);
                    } finally {
                        if (jjtc003)
                            jjtree.CloseNodeScope(jjtn003, 2);
                    }

                    break;
                default:
                    jjLa1[40] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }
        }
    }

    private void PrimaryExpression()
    {
        Token t;
        string? typeName = null;

        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
            case CharLiteral:
            case BackCharLiteral:
            case StringLiteral:
            case IntLiteral:
            case FltLiteral:
                switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                    case CharLiteral:
                        jj_consume_token(CharLiteral);

                        break;
                    case BackCharLiteral:
                        jj_consume_token(BackCharLiteral);

                        break;
                    case StringLiteral:
                        jj_consume_token(StringLiteral);

                        break;
                    case IntLiteral:
                        jj_consume_token(IntLiteral);

                        break;
                    case FltLiteral:
                        jj_consume_token(FltLiteral);

                        break;
                    default:
                        jjLa1[41] = jjGen;
                        jj_consume_token(-1);

                        throw new ParseException();
                }

                var jjtn001 = new AstConst(JjtConst);
                var jjtc001 = true;

                jjtree.OpenNodeScope(jjtn001);

                try {
                    jjtree.CloseNodeScope(jjtn001, 0);
                    jjtc001 = false;
                    jjtn001.Value = tokenSource.LiteralValue;
                } finally {
                    if (jjtc001)
                        jjtree.CloseNodeScope(jjtn001, 0);
                }

                break;
            case 46:
                jj_consume_token(46);

                var jjtn002 = new AstConst(JjtConst);
                var jjtc002 = true;

                jjtree.OpenNodeScope(jjtn002);

                try {
                    jjtree.CloseNodeScope(jjtn002, 0);
                    jjtc002 = false;
                    jjtn002.Value = true;
                } finally {
                    if (jjtc002)
                        jjtree.CloseNodeScope(jjtn002, 0);
                }

                break;
            case 47:
                jj_consume_token(47);

                var jjtn003 = new AstConst(JjtConst);
                var jjtc003 = true;

                jjtree.OpenNodeScope(jjtn003);

                try {
                    jjtree.CloseNodeScope(jjtn003, 0);
                    jjtc003 = false;
                    jjtn003.Value = false;
                } finally {
                    if (jjtc003)
                        jjtree.CloseNodeScope(jjtn003, 0);
                }

                break;
            case 48:
                var jjtn004 = new AstConst(JjtConst);
                var jjtc004 = true;

                jjtree.OpenNodeScope(jjtn004);

                try {
                    jj_consume_token(48);
                } finally {
                    if (jjtc004)
                        jjtree.CloseNodeScope(jjtn004, 0);
                }

                break;
            default:
                jjLa1[48] = jjGen;

                if (jj_2_4(2)) {
                    jj_consume_token(49);

                    var jjtn005 = new AstThisVarRef(JjtThisVarRef);
                    var jjtc005 = true;

                    jjtree.OpenNodeScope(jjtn005);

                    try {
                        jjtree.CloseNodeScope(jjtn005, 0);
                        jjtc005 = false;
                    } finally {
                        if (jjtc005)
                            jjtree.CloseNodeScope(jjtn005, 0);
                    }
                } else if (jj_2_5(2)) {
                    jj_consume_token(50);

                    var jjtn006 = new AstRootVarRef(JjtRootVarRef);
                    var jjtc006 = true;

                    jjtree.OpenNodeScope(jjtn006);

                    try {
                        jjtree.CloseNodeScope(jjtn006, 0);
                        jjtc006 = false;
                    } finally {
                        if (jjtc006)
                            jjtree.CloseNodeScope(jjtn006, 0);
                    }
                } else if (jj_2_6(2)) {
                    jj_consume_token(51);
                    t = jj_consume_token(Ident);

                    var jjtn007 = new AstVarRef(JjtVarRef);
                    var jjtc007 = true;

                    jjtree.OpenNodeScope(jjtn007);

                    try {
                        jjtree.CloseNodeScope(jjtn007, 0);
                        jjtc007 = false;
                        jjtn007.Name = t.Image;
                    } finally {
                        if (jjtc007)
                            jjtree.CloseNodeScope(jjtn007, 0);
                    }
                } else if (jj_2_7(2)) {
                    jj_consume_token(4);
                    jj_consume_token(52);
                    Expression();
                    jj_consume_token(53);

                    var jjtn008 = new AstConst(JjtConst);
                    var jjtc008 = true;

                    jjtree.OpenNodeScope(jjtn008);

                    try {
                        jjtree.CloseNodeScope(jjtn008, 1);
                        jjtc008 = false;
                        jjtn008.Value = jjtn008.GetChild(0);
                    } finally {
                        if (jjtc008)
                            jjtree.CloseNodeScope(jjtn008, 1);
                    }
                } else {
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 56:
                            StaticReference();

                            break;
                        default:
                            jjLa1[49] = jjGen;

                            if (jj_2_8(2)) {
                                ConstructorCall();
                            } else {
                                switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                    case Ident:
                                        if (jj_2_3(2))
                                            MethodCall();
                                        else
                                            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                                case Ident:
                                                    PropertyName();

                                                    break;
                                                default:
                                                    jjLa1[42] = jjGen;
                                                    jj_consume_token(-1);

                                                    throw new ParseException();
                                            }

                                        break;
                                    case 52:
                                    case DynamicSub:
                                        Index();

                                        break;
                                    case 44:
                                        jj_consume_token(44);
                                        Expression();
                                        jj_consume_token(45);

                                        break;
                                    case 54:
                                        jj_consume_token(54);

                                        var jjtn009 = new AstList(JjtList);
                                        var jjtc009 = true;

                                        jjtree.OpenNodeScope(jjtn009);

                                        try {
                                            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                                case 4:
                                                case 28:
                                                case 35:
                                                case 36:
                                                case 40:
                                                case 41:
                                                case 44:
                                                case 46:
                                                case 47:
                                                case 48:
                                                case 49:
                                                case 50:
                                                case 51:
                                                case 52:
                                                case 54:
                                                case 56:
                                                case 57:
                                                case Ident:
                                                case DynamicSub:
                                                case CharLiteral:
                                                case BackCharLiteral:
                                                case StringLiteral:
                                                case IntLiteral:
                                                case FltLiteral:
                                                    AssignmentExpression();

                                                    // label_14:
                                                    while (true) {
                                                        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                                            case 1:

                                                                break;
                                                            default:
                                                                jjLa1[43] = jjGen;

                                                                goto label_14;
                                                        }

                                                        jj_consume_token(1);
                                                        AssignmentExpression();
                                                    }

                                                    label_14:

                                                    break;
                                                default:
                                                    jjLa1[44] = jjGen;

                                                    break;
                                            }
                                        } catch (Exception) {
                                            if (jjtc009) {
                                                jjtree.ClearNodeScope();
                                                jjtc009 = false;
                                            } else
                                                jjtree.PopNode();

                                            throw;
                                        } finally {
                                            if (jjtc009)
                                                jjtree.CloseNodeScope(jjtn009, true);
                                        }

                                        jj_consume_token(55);

                                        break;
                                    default:
                                        jjLa1[50] = jjGen;

                                        if (jj_2_9(2)) {
                                            var jjtn010 = new AstMap(JjtMap);
                                            var jjtc010 = true;
                                            jjtree.OpenNodeScope(jjtn010);

                                            try {
                                                jj_consume_token(51);

                                                switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                                    case 56:
                                                        typeName = TypeReference();

                                                        break;
                                                    default:
                                                        jjLa1[45] = jjGen;

                                                        break;
                                                }

                                                jj_consume_token(54);

                                                switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                                    case 4:
                                                    case 28:
                                                    case 35:
                                                    case 36:
                                                    case 40:
                                                    case 41:
                                                    case 44:
                                                    case 46:
                                                    case 47:
                                                    case 48:
                                                    case 49:
                                                    case 50:
                                                    case 51:
                                                    case 52:
                                                    case 54:
                                                    case 56:
                                                    case 57:
                                                    case Ident:
                                                    case DynamicSub:
                                                    case CharLiteral:
                                                    case BackCharLiteral:
                                                    case StringLiteral:
                                                    case IntLiteral:
                                                    case FltLiteral:
                                                        KeyValueExpression();

                                                        // label_15:
                                                        while (true) {
                                                            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                                                case 1:

                                                                    break;
                                                                default:
                                                                    jjLa1[46] = jjGen;

                                                                    goto label_15;
                                                            }

                                                            jj_consume_token(1);
                                                            KeyValueExpression();
                                                        }

                                                        label_15:

                                                        break;
                                                    default:
                                                        jjLa1[47] = jjGen;

                                                        break;
                                                }

                                                jjtn010.TypeName = typeName;
                                                jj_consume_token(55);
                                            } catch (Exception) {
                                                if (jjtc010) {
                                                    jjtree.ClearNodeScope();
                                                    jjtc010 = false;
                                                } else
                                                    jjtree.PopNode();

                                                throw;
                                            } finally {
                                                if (jjtc010)
                                                    jjtree.CloseNodeScope(jjtn010, true);
                                            }
                                        } else {
                                            jj_consume_token(-1);

                                            throw new ParseException();
                                        }

                                        break;
                                }
                            }

                            break;
                    }
                }

                break;
        }
    }

    private void KeyValueExpression()
    {
        var jjtn001 = new AstKeyValue(JjtKeyValue);
        var jjtc001 = true;

        jjtree.OpenNodeScope(jjtn001);

        try {
            AssignmentExpression();

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 4:
                    jj_consume_token(4);
                    AssignmentExpression();

                    break;
                default:
                    jjLa1[51] = jjGen;

                    break;
            }
        } catch (Exception) {
            if (jjtc001) {
                jjtree.ClearNodeScope();
                jjtc001 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc001)
                jjtree.CloseNodeScope(jjtn001, true);
        }
    }

    private void StaticReference()
    {
        var typeName = TypeReference();

        if (jj_2_10(2))
            StaticMethodCall(typeName);
        else
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case Ident:
                    var t = jj_consume_token(Ident);
                    var jjtn001 = new AstStaticField(JjtStaticField);
                    var jjtc001 = true;

                    jjtree.OpenNodeScope(jjtn001);

                    try {
                        jjtree.CloseNodeScope(jjtn001, 0);
                        jjtc001 = false;
                        jjtn001.TypeName = typeName;
                        jjtn001.FieldName = t.Image;
                    } finally {
                        if (jjtc001)
                            jjtree.CloseNodeScope(jjtn001, 0);
                    }

                    break;
                default:
                    jjLa1[52] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }
    }

    private string TypeReference()
    {
        var result = "System.Math";

        jj_consume_token(56);

        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
            case Ident:
                result = TypeName();

                break;
            default:
                jjLa1[53] = jjGen;

                break;
        }

        jj_consume_token(56);

        return result;
    }

    private string TypeName()
    {
        var t = jj_consume_token(Ident);
        var result = new StringBuilder(t.Image);

        // label_16:
        while (true) {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 43:

                    break;
                default:
                    jjLa1[54] = jjGen;

                    goto label_16;
            }

            jj_consume_token(43);
            t = jj_consume_token(Ident);
            result.Append('.').Append(t.Image);
        }

        label_16:

        return result.ToString();
    }

    private void ConstructorCall()
    {
        /*@bgen(jjtree) Ctor */
        var jjtn000 = new AstCtor(JjtCtor);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            jj_consume_token(57);
            var typeName = TypeName();

            if (jj_2_11(2)) {
                jj_consume_token(44);

                switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                    case 4:
                    case 28:
                    case 35:
                    case 36:
                    case 40:
                    case 41:
                    case 44:
                    case 46:
                    case 47:
                    case 48:
                    case 49:
                    case 50:
                    case 51:
                    case 52:
                    case 54:
                    case 56:
                    case 57:
                    case Ident:
                    case DynamicSub:
                    case CharLiteral:
                    case BackCharLiteral:
                    case StringLiteral:
                    case IntLiteral:
                    case FltLiteral:
                        AssignmentExpression();

                        while (true) {
                            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                case 1:

                                    break;
                                default:
                                    jjLa1[55] = jjGen;

                                    goto label_17;
                            }

                            jj_consume_token(1);
                            AssignmentExpression();
                        }

                        label_17:

                        break;
                    default:
                        jjLa1[56] = jjGen;

                        break;
                }

                jj_consume_token(45);
                jjtree.CloseNodeScope(jjtn000, true);
                jjtc000 = false;
                jjtn000.TypeName = typeName;
            } else if (jj_2_12(2)) {
                jj_consume_token(52);
                jj_consume_token(53);
                jj_consume_token(54);

                var jjtn001 = new AstList(JjtList);
                var jjtc001 = true;

                jjtree.OpenNodeScope(jjtn001);

                try {
                    switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                        case 4:
                        case 28:
                        case 35:
                        case 36:
                        case 40:
                        case 41:
                        case 44:
                        case 46:
                        case 47:
                        case 48:
                        case 49:
                        case 50:
                        case 51:
                        case 52:
                        case 54:
                        case 56:
                        case 57:
                        case Ident:
                        case DynamicSub:
                        case CharLiteral:
                        case BackCharLiteral:
                        case StringLiteral:
                        case IntLiteral:
                        case FltLiteral:
                            AssignmentExpression();

                            // label_18:
                            while (true) {
                                switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                                    case 1:

                                        break;
                                    default:
                                        jjLa1[57] = jjGen;

                                        goto label_18;
                                }

                                jj_consume_token(1);
                                AssignmentExpression();
                            }

                            label_18:

                            break;
                        default:
                            jjLa1[58] = jjGen;

                            break;
                    }
                } catch (Exception) {
                    if (jjtc001) {
                        jjtree.ClearNodeScope();
                        jjtc001 = false;
                    } else
                        jjtree.PopNode();

                    throw;
                } finally {
                    if (jjtc001)
                        jjtree.CloseNodeScope(jjtn001, true);
                }

                jj_consume_token(55);
                jjtree.CloseNodeScope(jjtn000, true);
                jjtc000 = false;
                jjtn000.TypeName = typeName;
                jjtn000.IsArray = true;
            } else if (jj_2_13(2)) {
                jj_consume_token(52);
                AssignmentExpression();
                jj_consume_token(53);
                jjtree.CloseNodeScope(jjtn000, true);
                jjtc000 = false;
                jjtn000.TypeName = typeName;
                jjtn000.IsArray = true;
            } else {
                jj_consume_token(-1);

                throw new ParseException();
            }
        } catch (Exception) {
            if (jjtc000) {
                jjtree.ClearNodeScope();
                jjtc000 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    private void PropertyName()
    {
        /*@bgen(jjtree) Property */
        var jjtn000 = new AstProperty(JjtProperty);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            var t = jj_consume_token(Ident);

            var jjtn001 = new AstConst(JjtConst);
            var jjtc001 = true;

            jjtree.OpenNodeScope(jjtn001);

            try {
                jjtree.CloseNodeScope(jjtn001, true);
                jjtc001 = false;
                jjtn001.Value = t.Image;
            } finally {
                if (jjtc001)
                    jjtree.CloseNodeScope(jjtn001, true);
            }
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    private void StaticMethodCall(string typeName)
    {
        /*@bgen(jjtree) StaticMethod */
        var jjtn000 = new AstStaticMethod(JjtStaticMethod);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            var t = jj_consume_token(Ident);

            jj_consume_token(44);

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 4:
                case 28:
                case 35:
                case 36:
                case 40:
                case 41:
                case 44:
                case 46:
                case 47:
                case 48:
                case 49:
                case 50:
                case 51:
                case 52:
                case 54:
                case 56:
                case 57:
                case Ident:
                case DynamicSub:
                case CharLiteral:
                case BackCharLiteral:
                case StringLiteral:
                case IntLiteral:
                case FltLiteral:
                    AssignmentExpression();

                    // label_19:
                    while (true) {
                        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                            case 1:

                                break;
                            default:
                                jjLa1[59] = jjGen;

                                goto label_19;
                        }

                        jj_consume_token(1);
                        AssignmentExpression();
                    }

                    label_19:

                    break;
                default:
                    jjLa1[60] = jjGen;

                    break;
            }

            jj_consume_token(45);
            jjtree.CloseNodeScope(jjtn000, true);
            jjtc000 = false;
            jjtn000.TypeName = typeName;
            jjtn000.MethodName = t.Image;
        } catch (Exception) {
            if (jjtc000) {
                jjtree.ClearNodeScope();
                jjtc000 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    private void MethodCall()
    {
        /*@bgen(jjtree) Method */
        var jjtn000 = new AstMethod(JjtMethod);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            var t = jj_consume_token(Ident);

            jj_consume_token(44);

            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 4:
                case 28:
                case 35:
                case 36:
                case 40:
                case 41:
                case 44:
                case 46:
                case 47:
                case 48:
                case 49:
                case 50:
                case 51:
                case 52:
                case 54:
                case 56:
                case 57:
                case Ident:
                case DynamicSub:
                case CharLiteral:
                case BackCharLiteral:
                case StringLiteral:
                case IntLiteral:
                case FltLiteral:
                    AssignmentExpression();

                    // label_20:
                    while (true) {
                        switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                            case 1:

                                break;
                            default:
                                jjLa1[61] = jjGen;

                                goto label_20;
                        }

                        jj_consume_token(1);
                        AssignmentExpression();
                    }

                    label_20:

                    break;
                default:
                    jjLa1[62] = jjGen;

                    break;
            }

            jj_consume_token(45);
            jjtree.CloseNodeScope(jjtn000, true);
            jjtc000 = false;
            jjtn000.MethodName = t.Image;
        } catch (Exception) {
            if (jjtc000) {
                jjtree.ClearNodeScope();
                jjtc000 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    /**
     * Apply an expression to all elements of a collection, creating
     * a new collection as the result.
     */
    private void Projection()
    {
        /*@bgen(jjtree) Project */
        var jjtn000 = new AstProject(JjtProject);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            jj_consume_token(54);
            Expression();
            jj_consume_token(55);
        } catch (Exception) {
            if (jjtc000) {
                jjtree.ClearNodeScope();
                jjtc000 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    private void Selection()
    {
        if (jj_2_14(2))
            SelectAll();
        else if (jj_2_15(2))
            SelectFirst();
        else if (jj_2_16(2))
            SelectLast();
        else {
            jj_consume_token(-1);

            throw new ParseException();
        }
    }

    /**
     * Apply a bool expression to all elements of a collection, creating
     * a new collection containing those elements for which the expression
     * returned true.
     */
    private void SelectAll()
    {
        /*@bgen(jjtree) Select */
        var jjtn000 = new AstSelect(JjtSelect);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            jj_consume_token(54);
            jj_consume_token(3);
            Expression();
            jj_consume_token(55);
        } catch (Exception) {
            if (jjtc000) {
                jjtree.ClearNodeScope();
                jjtc000 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    /**
     * Apply a bool expression to all elements of a collection, creating
     * a new collection containing those elements for the first element
     * for which the expression returned true.
     */
    private void SelectFirst()
    {
        /*@bgen(jjtree) SelectFirst */
        var jjtn000 = new AstSelectFirst(JjtSelectFirst);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            jj_consume_token(54);
            jj_consume_token(11);
            Expression();
            jj_consume_token(55);
        } catch (Exception) {
            if (jjtc000) {
                jjtree.ClearNodeScope();
                jjtc000 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    /**
     * Apply a bool expression to all elements of a collection, creating
     * a new collection containing those elements for the first element
     * for which the expression returned true.
     */
    private void SelectLast()
    {
        /*@bgen(jjtree) SelectLast */
        var jjtn000 = new AstSelectLast(JjtSelectLast);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            jj_consume_token(54);
            jj_consume_token(58);
            Expression();
            jj_consume_token(55);
        } catch (Exception) {
            if (jjtc000) {
                jjtree.ClearNodeScope();
                jjtc000 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    private void Index()
    {
        /*@bgen(jjtree) Property */
        var jjtn000 = new AstProperty(JjtProperty);
        var jjtc000 = true;

        jjtree.OpenNodeScope(jjtn000);

        try {
            switch (fJjNtk == -1 ? jj_ntk() : fJjNtk) {
                case 52:
                    jj_consume_token(52);
                    Expression();
                    jj_consume_token(53);
                    jjtree.CloseNodeScope(jjtn000, true);
                    jjtc000 = false;
                    jjtn000.IndexedAccess = true;

                    break;
                case DynamicSub:
                    jj_consume_token(DynamicSub);

                    var jjtn001 = new AstConst(JjtConst);
                    var jjtc001 = true;

                    jjtree.OpenNodeScope(jjtn001);

                    try {
                        jjtree.CloseNodeScope(jjtn001, true);
                        jjtc001 = false;
                        jjtn001.Value = tokenSource.LiteralValue;
                    } finally {
                        if (jjtc001)
                            jjtree.CloseNodeScope(jjtn001, true);
                    }

                    jjtree.CloseNodeScope(jjtn000, true);
                    jjtc000 = false;
                    jjtn000.IndexedAccess = true;

                    break;
                default:
                    jjLa1[63] = jjGen;
                    jj_consume_token(-1);

                    throw new ParseException();
            }
        } catch (Exception) {
            if (jjtc000) {
                jjtree.ClearNodeScope();
                jjtc000 = false;
            } else
                jjtree.PopNode();

            throw;
        } finally {
            if (jjtc000)
                jjtree.CloseNodeScope(jjtn000, true);
        }
    }

    private bool jj_2_1(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_1();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(0, xla);
        }
    }

    private bool jj_2_2(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_2();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(1, xla);
        }
    }

    private bool jj_2_3(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_3();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(2, xla);
        }
    }

    private bool jj_2_4(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_4();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(3, xla);
        }
    }

    private bool jj_2_5(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_5();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(4, xla);
        }
    }

    private bool jj_2_6(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_6();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(5, xla);
        }
    }

    private bool jj_2_7(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_7();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(6, xla);
        }
    }

    private bool jj_2_8(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_8();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(7, xla);
        }
    }

    private bool jj_2_9(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_9();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(8, xla);
        }
    }

    private bool jj_2_10(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_10();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(9, xla);
        }
    }

    private bool jj_2_11(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_11();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(10, xla);
        }
    }

    private bool jj_2_12(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_12();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(11, xla);
        }
    }

    private bool jj_2_13(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_13();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(12, xla);
        }
    }

    private bool jj_2_14(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_14();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(13, xla);
        }
    }

    private bool jj_2_15(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_15();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(14, xla);
        }
    }

    private bool jj_2_16(int xla)
    {
        jjLa = xla;
        jjLastpos = jjScanpos = token;

        try {
            return !jj_3_16();
        } catch (LookaheadSuccess) {
            return true;
        } finally {
            jj_save(15, xla);
        }
    }

    private bool jj_3_5()
    {
        return jj_scan_token(50);
    }

    private bool jj_3_4()
    {
        return jj_scan_token(49);
    }

    private bool jj_3R_27()
    {
        return jj_3R_34();
    }

    private bool jj_3R_65()
    {
        return jj_scan_token(Ident);
    }

    private bool jj_3R_43()
    {
        return jj_3R_44();
    }

    private bool jj_3R_56()
    {
        return jj_scan_token(48);
    }

    private bool jj_3R_55()
    {
        return jj_scan_token(47);
    }

    private bool jj_3R_54()
    {
        return jj_scan_token(46);
    }

    private bool jj_3R_31()
    {
        return jj_3R_27();
    }

    private bool jj_3_13()
    {
        return jj_scan_token(52) || jj_3R_27();
    }

    private bool jj_3R_53()
    {
        var xsp = jjScanpos;

        if (jj_scan_token(73)) {
            jjScanpos = xsp;

            if (jj_scan_token(76)) {
                jjScanpos = xsp;

                if (jj_scan_token(79)) {
                    jjScanpos = xsp;

                    if (jj_scan_token(80)) {
                        jjScanpos = xsp;

                        if (jj_scan_token(81))
                            return true;
                    }
                }
            }
        }

        return false;
    }

    private bool jj_3R_26()
    {
        return jj_3R_27();
    }

    private bool jj_3R_52()
    {
        var xsp = jjScanpos;

        if (jj_3R_53()) {
            jjScanpos = xsp;

            if (jj_3R_54()) {
                jjScanpos = xsp;

                if (jj_3R_55()) {
                    jjScanpos = xsp;

                    if (jj_3R_56()) {
                        jjScanpos = xsp;

                        if (jj_3_4()) {
                            jjScanpos = xsp;

                            if (jj_3_5()) {
                                jjScanpos = xsp;

                                if (jj_3_6()) {
                                    jjScanpos = xsp;

                                    if (jj_3_7()) {
                                        jjScanpos = xsp;

                                        if (jj_3R_57()) {
                                            jjScanpos = xsp;

                                            if (jj_3_8()) {
                                                jjScanpos = xsp;

                                                if (jj_3R_58()) {
                                                    jjScanpos = xsp;

                                                    if (jj_3R_59()) {
                                                        jjScanpos = xsp;

                                                        if (jj_3R_60()) {
                                                            jjScanpos = xsp;

                                                            if (jj_3R_61()) {
                                                                jjScanpos = xsp;

                                                                if (jj_3_9()) return true;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        return false;
    }

    private bool jj_3R_42()
    {
        return jj_3R_43();
    }

    private bool jj_3_12()
    {
        return jj_scan_token(52) || jj_scan_token(53);
    }

    private bool jj_3_11()
    {
        if (jj_scan_token(44))
            return true;

        var xsp = jjScanpos;

        if (jj_3R_26())
            jjScanpos = xsp;

        return jj_scan_token(45);
    }

    private bool jj_3R_67()
    {
        return jj_scan_token(DynamicSub);
    }

    private bool jj_3_2()
    {
        return jj_3R_22();
    }

    private bool jj_3R_66()
    {
        return jj_scan_token(52);
    }

    private bool jj_3R_64()
    {
        var xsp = jjScanpos;

        if (jj_3R_66()) {
            jjScanpos = xsp;

            if (jj_3R_67())
                return true;
        }

        return false;
    }

    private bool jj_3_1()
    {
        return jj_3R_21();
    }

    private bool jj_3R_23()
    {
        return jj_scan_token(57) || jj_3R_32();
    }

    private bool jj_3R_41()
    {
        return jj_3R_42();
    }

    private bool jj_3R_30()
    {
        return jj_scan_token(54) || jj_scan_token(58);
    }

    private bool jj_3R_32()
    {
        return jj_scan_token(Ident);
    }

    private bool jj_3R_51()
    {
        return jj_3R_52();
    }

    private bool jj_3R_29()
    {
        return jj_scan_token(54) || jj_scan_token(11);
    }

    private bool jj_3R_40()
    {
        return jj_3R_41();
    }

    private bool jj_3R_33()
    {
        return jj_scan_token(56);
    }

    private bool jj_3R_63()
    {
        return jj_3R_65();
    }

    private bool jj_3R_28()
    {
        return jj_scan_token(54) || jj_scan_token(3);
    }

    private bool jj_3R_50()
    {
        return jj_3R_51();
    }

    private bool jj_3R_39()
    {
        return jj_3R_40();
    }

    private bool jj_3_10()
    {
        return jj_3R_25();
    }

    private bool jj_3R_24()
    {
        return jj_3R_33();
    }

    private bool jj_3R_49()
    {
        var xsp = jjScanpos;

        if (jj_scan_token(41)) {
            jjScanpos = xsp;

            if (jj_scan_token(28))
                return true;
        }

        return false;
    }

    private bool jj_3R_48()
    {
        return jj_scan_token(40);
    }

    private bool jj_3_16()
    {
        return jj_3R_30();
    }

    private bool jj_3R_47()
    {
        return jj_scan_token(35);
    }

    private bool jj_3_15()
    {
        return jj_3R_29();
    }

    private bool jj_3R_38()
    {
        return jj_3R_39();
    }

    private bool jj_3R_46()
    {
        return jj_scan_token(36);
    }

    private bool jj_3_14()
    {
        return jj_3R_28();
    }

    private bool jj_3R_62()
    {
        return jj_3R_33();
    }

    private bool jj_3R_45()
    {
        var xsp = jjScanpos;

        if (jj_3R_46()) {
            jjScanpos = xsp;

            if (jj_3R_47()) {
                jjScanpos = xsp;

                if (jj_3R_48()) {
                    jjScanpos = xsp;

                    if (jj_3R_49()) {
                        jjScanpos = xsp;

                        if (jj_3R_50())
                            return true;
                    }
                }
            }
        }

        return false;
    }

    private bool jj_3R_37()
    {
        return jj_3R_38();
    }

    private bool jj_3R_22()
    {
        return jj_scan_token(54) || jj_3R_31();
    }

    private bool jj_3_9()
    {
        if (jj_scan_token(51))
            return true;

        var xsp = jjScanpos;

        if (jj_3R_24())
            jjScanpos = xsp;

        return jj_scan_token(54);
    }

    private bool jj_3R_36()
    {
        return jj_3R_37();
    }

    private bool jj_3R_61()
    {
        return jj_scan_token(54);
    }

    private bool jj_3R_60()
    {
        return jj_scan_token(44);
    }

    private bool jj_3R_59()
    {
        return jj_3R_64();
    }

    private bool jj_3_3()
    {
        return jj_3R_21();
    }

    private bool jj_3R_21()
    {
        return jj_scan_token(Ident) || jj_scan_token(44);
    }

    private bool jj_3R_58()
    {
        var xsp = jjScanpos;

        if (jj_3_3()) {
            jjScanpos = xsp;

            if (jj_3R_63())
                return true;
        }

        return false;
    }

    private bool jj_3R_35()
    {
        return jj_3R_36();
    }

    private bool jj_3R_44()
    {
        return jj_3R_45();
    }

    private bool jj_3_8()
    {
        return jj_3R_23();
    }

    private bool jj_3R_57()
    {
        return jj_3R_62();
    }

    private bool jj_3R_34()
    {
        return jj_3R_35();
    }

    private bool jj_3_7()
    {
        return jj_scan_token(4) || jj_scan_token(52);
    }

    private bool jj_3R_25()
    {
        return jj_scan_token(Ident) || jj_scan_token(44);
    }

    private bool jj_3_6()
    {
        return jj_scan_token(51) || jj_scan_token(Ident);
    }

    private ParserTokenManager tokenSource;

    private readonly JavaCharStream jjInputStream;

    private Token token;

    private Token jjNt;

    private int fJjNtk;

    private Token jjScanpos, jjLastpos;

    private int jjLa;

    private int jjGen;

    private readonly int[] jjLa1 = new int[64];

    private static uint[] fJjLa10;

    private static uint[] fJjLa11;

    private static uint[] fJjLa12;

    static Parser()
    {
        jj_la1_0();
        jj_la1_1();
        jj_la1_2();
    }

    private static void jj_la1_0()
    {
        fJjLa10 = [
            0x2, 0x4, 0x8, 0x60, 0x60, 0x180, 0x180, 0x600, 0x600, 0x1800, 0x1800, 0x6000, 0x6000, 0x78000, 0x18000,
            0x60000, 0x78000, 0x1ff80000, 0x180000, 0x600000, 0x1800000, 0x6000000, 0x1ff80000, 0xe0000000, 0x60000000,
            0x80000000, 0x0, 0xe0000000, 0x0, 0x0, 0x0, 0x0, 0x10000000, 0x0, 0x0, 0x10000010, 0x0, 0x0, 0x0, 0x0, 0x0,
            0x0, 0x0, 0x2, 0x10000010, 0x0, 0x2, 0x10000010, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0, 0x2, 0x10000010, 0x2,
            0x10000010, 0x2, 0x10000010, 0x2, 0x10000010, 0x0
        ];
    }

    private static void jj_la1_1()
    {
        fJjLa11 = [
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
            0x0, 0x0, 0x7, 0x0, 0x1, 0x6, 0x7, 0x18, 0x18, 0xe0, 0xe0, 0x200, 0x800, 0x400, 0x35fd318, 0x101800, 0x0,
            0x400000, 0x401000, 0x101800, 0x0, 0x0, 0x0, 0x35fd318, 0x1000000, 0x0, 0x35fd318, 0x1c000, 0x1000000,
            0x501000, 0x0, 0x0, 0x0, 0x800, 0x0, 0x35fd318, 0x0, 0x35fd318, 0x0, 0x35fd318, 0x0, 0x35fd318, 0x100000
        ];
    }

    private static void jj_la1_2()
    {
        fJjLa12 = [
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x39209, 0x8, 0x1, 0x0, 0x1, 0x8,
            0x39200, 0x1, 0x0, 0x39209, 0x0, 0x0, 0x39209, 0x39200, 0x0, 0x9, 0x0, 0x1, 0x1, 0x0, 0x0, 0x39209, 0x0,
            0x39209, 0x0, 0x39209, 0x0, 0x39209, 0x8
        ];
    }

    private readonly JjCalls[] jj2Rtns = new JjCalls[16];

    private bool jjRescan;

    private int jjGc;

    public Parser(TextReader stream)
    {
        jjInputStream = new JavaCharStream(stream, 1, 1);
        tokenSource = new ParserTokenManager(jjInputStream);
        token = new Token();
        fJjNtk = -1;
        jjGen = 0;

        for (var i = 0; i < 64; i++)
            jjLa1[i] = -1;

        for (var i = 0; i < jj2Rtns.Length; i++)
            jj2Rtns[i] = new JjCalls();
    }

    private Token jj_consume_token(int kind)
    {
        Token oldToken;

        if ((oldToken = token).Next != null)
            token = token.Next;
        else
            token = token.Next = tokenSource.GetNextToken();

        fJjNtk = -1;

        if (token.Kind == kind) {
            jjGen++;

            if (++jjGc > 100) {
                jjGc = 0;

                for (var i = 0; i < jj2Rtns.Length; i++) {
                    var c = jj2Rtns[i];

                    while (c != null) {
                        if (c.gen < jjGen) c.first = null;
                        c = c.next;
                    }
                }
            }

            return token;
        }

        token = oldToken;
        jjKind = kind;

        throw GenerateParseException();
    }

    private class LookaheadSuccess : Exception;

    private readonly LookaheadSuccess jjLs = new();

    private bool jj_scan_token(int kind)
    {
        if (jjScanpos == jjLastpos) {
            jjLa--;

            if (jjScanpos.Next == null)
                jjLastpos = jjScanpos = jjScanpos.Next = tokenSource.GetNextToken();
            else
                jjLastpos = jjScanpos = jjScanpos.Next;
        } else
            jjScanpos = jjScanpos.Next;

        if (jjRescan) {
            var i = 0;
            var tok = token;

            while (tok != null && tok != jjScanpos) {
                i++;
                tok = tok.Next;
            }

            if (tok != null)
                jj_add_error_token(kind, i);
        }

        if (jjScanpos.Kind != kind)
            return true;

        if (jjLa == 0 && jjScanpos == jjLastpos)
            throw jjLs;

        return false;
    }

    public Token GetNextToken()
    {
        if (token.Next != null)
            token = token.Next;
        else
            token = token.Next = tokenSource.GetNextToken();

        fJjNtk = -1;
        jjGen++;

        return token;
    }

    public Token GetToken(int index)
    {
        var t = token;

        for (var i = 0; i < index; i++)
            if (t.Next != null)
                t = t.Next;
            else
                t = t.Next = tokenSource.GetNextToken();

        return t;
    }

    private int jj_ntk()
    {
        if ((jjNt = token.Next) == null)
            return fJjNtk = (token.Next = tokenSource.GetNextToken()).Kind;

        return fJjNtk = jjNt.Kind;
    }

    private readonly ArrayList jjExpentries = new();

    private int[] jjExpentry;

    private int jjKind = -1;

    private readonly int[] jjLasttokens = new int[100];

    private int jjEndpos;

    private void jj_add_error_token(int kind, int pos)
    {
        if (pos >= 100)
            return;

        if (pos == jjEndpos + 1)
            jjLasttokens[jjEndpos++] = kind;
        else if (jjEndpos != 0) {
            jjExpentry = new int[jjEndpos];

            for (var i = 0; i < jjEndpos; i++)
                jjExpentry[i] = jjLasttokens[i];

            var exists = false;

            for (var e = jjExpentries.GetEnumerator(); e.MoveNext();) {
                var oldentry = (int[])e.Current;

                if (oldentry.Length == jjExpentry.Length) {
                    exists = true;

                    for (var i = 0; i < jjExpentry.Length; i++)
                        if (oldentry[i] != jjExpentry[i]) {
                            exists = false;

                            break;
                        }

                    if (exists)
                        break;
                }
            }

            if (!exists)
                jjExpentries.Add(jjExpentry);

            if (pos != 0)
                jjLasttokens[(jjEndpos = pos) - 1] = kind;
        }
    }

    private ParseException GenerateParseException()
    {
        jjExpentries.Clear();

        var la1Tokens = new bool[86];

        for (var i = 0; i < 86; i++)
            la1Tokens[i] = false;

        if (jjKind >= 0) {
            la1Tokens[jjKind] = true;
            jjKind = -1;
        }

        for (var i = 0; i < 64; i++)
            if (jjLa1[i] == jjGen)
                for (var j = 0; j < 32; j++) {
                    if ((fJjLa10[i] & (1 << j)) != 0)
                        la1Tokens[j] = true;

                    if ((fJjLa11[i] & (1 << j)) != 0)
                        la1Tokens[32 + j] = true;

                    if ((fJjLa12[i] & (1 << j)) != 0)
                        la1Tokens[64 + j] = true;
                }

        for (var i = 0; i < 86; i++)
            if (la1Tokens[i]) {
                jjExpentry = new int[1];
                jjExpentry[0] = i;
                jjExpentries.Add(jjExpentry);
            }

        jjEndpos = 0;
        jj_rescan_token();
        jj_add_error_token(0, 0);

        var exptokseq = new int[jjExpentries.Count][];

        for (var i = 0; i < jjExpentries.Count; i++)
            exptokseq[i] = (int[])jjExpentries[i];

        return new ParseException();
    }

    private void jj_rescan_token()
    {
        jjRescan = true;

        for (var i = 0; i < 16; i++) {
            var p = jj2Rtns[i];

            do {
                if (p.gen > jjGen) {
                    jjLa = p.arg;
                    jjLastpos = jjScanpos = p.first;

                    switch (i) {
                        case 0: jj_3_1(); break;
                        case 1: jj_3_2(); break;
                        case 2: jj_3_3(); break;
                        case 3: jj_3_4(); break;
                        case 4: jj_3_5(); break;
                        case 5: jj_3_6(); break;
                        case 6: jj_3_7(); break;
                        case 7: jj_3_8(); break;
                        case 8: jj_3_9(); break;
                        case 9: jj_3_10(); break;
                        case 10: jj_3_11(); break;
                        case 11: jj_3_12(); break;
                        case 12: jj_3_13(); break;
                        case 13: jj_3_14(); break;
                        case 14: jj_3_15(); break;
                        case 15: jj_3_16(); break;
                    }
                }

                p = p.next;
            } while (p != null);
        }

        jjRescan = false;
    }

    private void jj_save(int index, int xla)
    {
        var p = jj2Rtns[index];

        while (p.gen > jjGen) {
            if (p.next == null) {
                p = p.next = new JjCalls();

                break;
            }

            p = p.next;
        }

        p.gen = jjGen + xla - jjLa;
        p.first = token;
        p.arg = xla;
    }

    private class JjCalls {
        internal int gen;

        internal Token first;

        internal int arg;

        internal JjCalls next;
    }
}
