/* Generated By:JJTree: Do not edit this line. */

namespace OGNL.Parser;

internal abstract class ParserTreeConstants : ParserConstants {
    protected const int JJTSEQUENCE = 1;

    protected const int JJTASSIGN = 2;

    protected const int JJTTEST = 3;

    protected const int JJTOR = 4;

    protected const int JJTAND = 5;

    protected const int JJTBITOR = 6;

    protected const int JJTXOR = 7;

    protected const int JJTBITAND = 8;

    protected const int JJTEQ = 9;

    protected const int JJTNOTEQ = 10;

    protected const int JJTLESS = 11;

    protected const int JJTGREATER = 12;

    protected const int JJTLESSEQ = 13;

    protected const int JJTGREATEREQ = 14;

    protected const int JJTIN = 15;

    protected const int JJTNOTIN = 16;

    protected const int JJTSHIFTLEFT = 17;

    protected const int JJTSHIFTRIGHT = 18;

    protected const int JJTUNSIGNEDSHIFTRIGHT = 19;

    protected const int JJTADD = 20;

    protected const int JJTSUBTRACT = 21;

    protected const int JJTMULTIPLY = 22;

    protected const int JJTDIVIDE = 23;

    protected const int JJTREMAINDER = 24;

    protected const int JJTNEGATE = 25;

    protected const int JJTBITNEGATE = 26;

    protected const int JJTNOT = 27;

    protected const int JJTINSTANCEOF = 28;

    protected const int JJTCHAIN = 29;

    protected const int JJTEVAL = 30;

    protected const int JJTCONST = 31;

    protected const int JJTTHISVARREF = 32;

    protected const int JJTROOTVARREF = 33;

    protected const int JJTVARREF = 34;

    protected const int JJTLIST = 35;

    protected const int JJTMAP = 36;

    protected const int JJTKEYVALUE = 37;

    protected const int JJTSTATICFIELD = 38;

    protected const int JJTCTOR = 39;

    protected const int JJTPROPERTY = 40;

    protected const int JJTSTATICMETHOD = 41;

    protected const int JJTMETHOD = 42;

    protected const int JJTPROJECT = 43;

    protected const int JJTSELECT = 44;

    protected const int JJTSELECTFIRST = 45;

    protected const int JJTSELECTLAST = 46;

    public static readonly string[] JjtNodeName = [
        "void",
        "Sequence",
        "Assign",
        "Test",
        "Or",
        "And",
        "BitOr",
        "Xor",
        "BitAnd",
        "Eq",
        "NotEq",
        "Less",
        "Greater",
        "LessEq",
        "GreaterEq",
        "In",
        "NotIn",
        "ShiftLeft",
        "ShiftRight",
        "UnsignedShiftRight",
        "Add",
        "Subtract",
        "Multiply",
        "Divide",
        "Remainder",
        "Negate",
        "BitNegate",
        "Not",
        "Instanceof",
        "Chain",
        "Eval",
        "Const",
        "ThisVarRef",
        "RootVarRef",
        "VarRef",
        "List",
        "IDictionary",
        "KeyValue",
        "StaticField",
        "Ctor",
        "Property",
        "StaticMethod",
        "Method",
        "Project",
        "Select",
        "SelectFirst",
        "SelectLast"
    ];
}
