/* Generated By:JJTree: Do not edit this line. */

namespace OGNL.Parser;

internal static class ParserTreeConstants {
    public const int JjtSequence = 1;

    public const int JjtAssign = 2;

    public const int JjtTest = 3;

    public const int JjtOr = 4;

    public const int JjtAnd = 5;

    public const int JjtBitOr = 6;

    public const int JjtXor = 7;

    public const int JjtBitAnd = 8;

    public const int JjtEq = 9;

    public const int JjtNotEq = 10;

    public const int JjtLess = 11;

    public const int JjtGreater = 12;

    public const int JjtLessEq = 13;

    public const int JjtGreaterEq = 14;

    public const int JjtIn = 15;

    public const int JjtNotIn = 16;

    public const int JjtShiftLeft = 17;

    public const int JjtShiftRight = 18;

    public const int JjtUnsignedShiftRight = 19;

    public const int JjtAdd = 20;

    public const int JjtSubtract = 21;

    public const int JjtMultiply = 22;

    public const int JjtDivide = 23;

    public const int JjtRemainder = 24;

    public const int JjtNegate = 25;

    public const int JjtBitNegate = 26;

    public const int JjtNot = 27;

    public const int JjtInstanceOf = 28;

    public const int JjtChain = 29;

    public const int JjtEval = 30;

    public const int JjtConst = 31;

    public const int JjtThisVarRef = 32;

    public const int JjtRootVarRef = 33;

    public const int JjtVarRef = 34;

    public const int JjtList = 35;

    public const int JjtMap = 36;

    public const int JjtKeyValue = 37;

    public const int JjtStaticField = 38;

    public const int JjtCtor = 39;

    public const int JjtProperty = 40;

    public const int JjtStaticMethod = 41;

    public const int JjtMethod = 42;

    public const int JjtProject = 43;

    public const int JjtSelect = 44;

    public const int JjtSelectFirst = 45;

    public const int JjtSelectLast = 46;

    public static readonly string[] JjtNodeName = [
        "void",
        "Sequence",
        "Assign",
        "Test",
        "Or",
        "And",
        "BitOr",
        "Xor",
        "BitAnd",
        "Eq",
        "NotEq",
        "Less",
        "Greater",
        "LessEq",
        "GreaterEq",
        "In",
        "NotIn",
        "ShiftLeft",
        "ShiftRight",
        "UnsignedShiftRight",
        "Add",
        "Subtract",
        "Multiply",
        "Divide",
        "Remainder",
        "Negate",
        "BitNegate",
        "Not",
        "Instanceof",
        "Chain",
        "Eval",
        "Const",
        "ThisVarRef",
        "RootVarRef",
        "VarRef",
        "List",
        "IDictionary",
        "KeyValue",
        "StaticField",
        "Ctor",
        "Property",
        "StaticMethod",
        "Method",
        "Project",
        "Select",
        "SelectFirst",
        "SelectLast"
    ];
}
