using System.Text;

/* Generated By:JavaCC: Do not edit this line. */
namespace OGNL.Parser;

internal class TokenMgrError : Exception {
    /**
     * Replaces unprintable characters by their espaced (or unicode escaped)
     * equivalents in the given string
     */
    private static string AddEscapes(string str)
    {
        var retval = new StringBuilder();
        char ch;

        foreach (var t in str) {
            switch (t) {
                case (char)0:
                    continue;
                case '\b':
                    retval.Append("\\b");

                    continue;
                case '\t':
                    retval.Append("\\t");

                    continue;
                case '\n':
                    retval.Append("\\n");

                    continue;
                case '\f':
                    retval.Append("\\f");

                    continue;
                case '\r':
                    retval.Append("\\r");

                    continue;
                case '\"':
                    retval.Append("\\\"");

                    continue;
                case '\'':
                    retval.Append("\\\'");

                    continue;
                case '\\':
                    retval.Append("\\\\");

                    continue;
                default:
                    if ((ch = t) < 0x20 || ch > 0x7e) {
                        var s = "0000" + ((int)ch).ToString("X"); // Integer.ToString(ch, 16);
                        retval.Append("\\u" + s.Substring(s.Length - 4, s.Length));
                    } else {
                        retval.Append(ch);
                    }

                    continue;
            }
        }

        return retval.ToString();
    }

    /**
     * Returns a detailed message for the Error when it is thrown by the
     * token manager to indicate a lexical error.
     * Parameters :
     *    EOFSeen     : indicates if EOF caused the lexicl error
     *    curLexState : lexical state in which this error occured
     *    errorLine   : line number when the error occured
     *    errorColumn : column number when the error occured
     *    errorAfter  : prefix that was seen before this error occured
     *    curchar     : the offending character
     * Note: You can customize the lexical error message by modifying this method.
     */
    private static string LexicalError(bool eofSeen, int errorLine,
        int errorColumn, string errorAfter, char curChar)
    {
        return "Lexical error at line " +
            errorLine + ", column " +
            errorColumn + ".  Encountered: " +
            (eofSeen ? "<EOF> " : "\"" + AddEscapes(curChar.ToString()) + "\"" + " (" + (int)curChar + "), ") +
            "after : \"" + AddEscapes(errorAfter) + "\"";
    }

    /*
     * Constructors of various flavors follow.
     */

    private TokenMgrError(string message) : base(message)
    {
    }

    public TokenMgrError(bool EOFSeen, int errorLine, int errorColumn,
        string errorAfter, char curChar) : this(LexicalError(EOFSeen,
        errorLine, errorColumn, errorAfter, curChar))
    {
    }
}
