// Copyright 2009 Jeffrey Cameron
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Diagnostics;
using System.Globalization;
using Concordion.Api;
using Concordion.Api.Listener;

namespace Concordion.Internal.Listener;

public class PageFooterRenderer : SpecificationProcessingListener {
    private const string ConcordionWebsiteUrl = "https://concordion.org/";

    private readonly Stopwatch stopwatch = new();

    public void BeforeProcessingSpecification(
        SpecificationProcessingEvent processingEvent)
    {
        stopwatch.Start();
    }

    public void AfterProcessingSpecification(
        SpecificationProcessingEvent processingEvent)
    {
        stopwatch.Stop();
        AddFooterToDocument(processingEvent.RootElement,
            stopwatch.ElapsedMilliseconds);
    }

    private void AddFooterToDocument(Element rootElement, long millisTaken)
    {
        var body = rootElement.GetFirstChildElement("body");

        if (body == null)
            return;

        var footer = new Element("div");

        footer.AddStyleClass("footer");
        AddResultsGeneratedBy(footer);
        AddDateGeneratedAt(millisTaken, footer);
        body.AppendChild(footer);
    }

    private void AddDateGeneratedAt(long millisTaken, Element footer)
    {
        var dateDiv = new Element("div");

        dateDiv.AddStyleClass("testTime");
        dateDiv.AppendText("in " + (millisTaken + 1) + " ms ");
        dateDiv.AppendText(DateTime.Now.ToString(
            "'on' dd-MMM-yyyy 'at' HH:mm:ss zzz",
            CultureInfo.InvariantCulture));
        footer.AppendChild(dateDiv);
    }

    private void AddResultsGeneratedBy(Element footer)
    {
        footer.AppendText("Results generated by ");

        var link = new Element("a");

        link.AppendText("Concordion");
        link.AddAttribute("href", ConcordionWebsiteUrl);
        link.AddAttribute("style",
            "font-weight: bold; text-decoration: none; color: #89C;");
        footer.AppendChild(link);
    }
}
